### ISSUE TITLE
[Question] Add handling for seaplane

### ISSUE THREAD

**Issue by GoldDust69** [QIN2DIM/hcaptcha-challenger#10]
Hello, love your work. I've just ran into the following issue though:

When a seaplane is displayed the label returns `None` so it doesn't solve. If adding seaplane to the recognition is too time consuming or tricky, perhaps you could handle this by refreshing the capture window instead to get a new image? 

I tried to grab images but it looks like only completed captchas are stored in `temp_cache`

![Resp](https://user-images.githubusercontent.com/46097438/156904468-84154fec-8d86-49ef-bc14-d672e4985bbe.png)
![Seaplane](https://user-images.githubusercontent.com/46097438/156904469-f12194dc-20b6-4739-b3bf-f3f805ce32fe.png)

**Comment by QIN2DIM** [comment]
🥂 Thank you for your support.

## Active avoidance mechanism

For this issue, let me first make it clear that it is not a bug. I have designed an `active avoidance` mechanism in the program. 

You can find it in the source code:

https://github.com/QIN2DIM/hcaptcha-challenger/blob/3c40a941f15cc8e10c34d90f4f736cc1ddbdffc6/src/services/hcaptcha_challenger/core.py#L42-L57

I treat challenge labels that do not appear in the `label_alias` dictionary as "new label" that I encountered by accident. In this case the program will actively avoid the challenge and ask the upper level driver to refresh the challenge elements. Such decisions can avoid unnecessary hassles. 

Therefore, for demonstration purposes, I considered `seaplane` as a "new label" and actively kicked it out of the `label_alias` dictionary.

## Passive avoidance mechanism

On the other hand, I offer a `retreat` method for avoiding challenges that some known models cannot handle. Again, for demonstration purposes, there is a default challenge label `seaplane` in this list.

You can find it in the source code:

https://github.com/QIN2DIM/hcaptcha-challenger/blob/3c40a941f15cc8e10c34d90f4f736cc1ddbdffc6/src/services/hcaptcha_challenger/core.py#L97-L102

## Refresh the hCAPTCHA elements

As you can see from the above, it is essential to actively refresh the challenge elements. However, it is clear that the current project lacks the mechanisms described above. 

This project was spun off from a previous project I was working on and there are still some features that have not been migrated.I will add this mechanism where necessary in a future version, but if you want to use `hcapcha-challenger` in your own projects I think you know how to do it.

**Comment by GoldDust69** [comment]
Thank you so much for your detailed response!

I've re-read the code after your explanation and now I understand how you handle this. For my project I've now added a simple refresh and retry until a valid label is returned.

I look forward to seeing what changes are made in the future :)

**Comment by GoldDust69** [comment]
Thank you so much for your detailed response!

I've re-read the code after your explanation and now I understand how you handle this. For my project I've now added a simple refresh and retry until a valid label is returned.

I look forward to seeing what changes are made in the future :)
