### ISSUE TITLE
[Challenge] рarrot

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#102]
### Prompt[en]

Please click each image containing a parrot

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

![img_v2_3b98b4ab-62a8-4bb1-99ba-5dea64a7876g](https://user-images.githubusercontent.com/62018067/181522237-decaf71d-685b-43ed-a3fe-33d0cb2a51e6.png)

**Comment by huozhenlin** [comment]
动物世界大集合来了
