### ISSUE TITLE
[Question] Captcha decoding error

### ISSUE THREAD

**Issue by 1eminozlu** [QIN2DIM/hcaptcha-challenger#109]
There are too many pictures that he can't decipher. How can I fix this situation?
My ip address is blocked because it can't resolve.

**Comment by liuming9157** [comment]
I think it works well because I am using it these days. But it has no model of dogs with closed eyes. You better show the error detail here.

**Comment by 1eminozlu** [comment]
I showed my problem with video

http://e.pc.cd/SSxotalK

**Comment by QIN2DIM** [comment]
These challenges have been solved long ago, and you need to keep an eye on the [pluggable ONNX models](https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/objects.yaml) updates and pull the latest features.

**Comment by 1eminozlu** [comment]
> These challenges have been solved long ago, and you need to keep an eye on the [pluggable ONNX models](https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/objects.yaml) updates and pull the latest features.

For some reason, even though I'm using the latest version, it's still making an error.

**Comment by QIN2DIM** [comment]
The situation is very complex, so you need to provide the full log as well as a contextual description.
