### ISSUE TITLE
[Question] only integer scalar arrays can be converted to a scalar index 

### ISSUE THREAD

**Issue by adv-zl** [QIN2DIM/hcaptcha-challenger#11]
Hello, I have exception on yolo.py line: 185 `return [str(self.classes[class_ids[i]]) for i in indices]`

> only integer scalar arrays can be converted to a scalar index

How to fix it?

**Comment by QIN2DIM** [comment]
```bash
pip install opencv-python~=4.5.5.62 numpy>=1.21.5
```
