### ISSUE TITLE
[Question] Request based solving

### ISSUE THREAD

**Issue by FuckingToasters** [QIN2DIM/hcaptcha-challenger#110]
## Brief description
I'm creating a Application which need to solve captchas but i'm not using selenium for the Application.
Is it possible to solve the captcha with this repo for request based tools (get captchatoken)?

Regards,
FuckingToasters

**Comment by Memexurer** [comment]
you could integrate captcha AI to h0nde's request only solver.
https://github.com/GRUpA-HAKERSKA-PIOTRUS/haram-solver
I made something like this here, but it has an outdated hcaptcha-challenger version (pasted AI code there because couldn't find any APIs)

**Comment by Memexurer** [comment]
and of course, you still need a browser for solving hsw thing

**Comment by cheungchingli** [comment]
> you could integrate captcha AI to h0nde's request only solver. https://github.com/GRUpA-HAKERSKA-PIOTRUS/haram-solver I made something like this here, but it has an outdated hcaptcha-challenger version (pasted AI code there because couldn't find any APIs)

can't open this link

**Comment by beiyuouo** [comment]
@FuckingToasters @cheungchingli Welcome to experience @captcha-challenger free api (under alpha test), looking forward to your feedback!
Document: https://captcha-challenger.github.io/docs/#/hcaptcha/

**Comment by FuckingToasters** [comment]
I didn't rly worked with this so far but if i do, i can share my experience with it.
