### ISSUE TITLE
[Question] Use of proxy to bypass IP limitation

### ISSUE THREAD

**Issue by SoloQTKiller** [QIN2DIM/hcaptcha-challenger#111]
## Tip to bypass IP limitation

Well I currently work with a residential proxy, whose connection model is as follows:

```markdown
user:password@54.236.156.20:31112
```
I would like to know how to insert the use of proxy in your project to be able to circumvent possible limitations by IP

**Comment by QIN2DIM** [comment]
Currently, there are some dependency issues that need to be addressed with this project. I personally believe that the headless browser feature of the challenger driver is being identified, causing the guest IP to be flagged as a high threat target.

**Comment by kuuyby9duoi** [comment]
> 
I don't know anything about Python but the way I break the code is very good.
I have added src\apis\challenge.py right after the first try of the loop to change the proxy before starting a Captcha Session. You can also add to after line _if resp == challenger.CHALLENGE_SUCCESS:_   or _def is_successful_at_the_demo_site():_ At Sevices\hcaptcha_challenger\core.py this applies to after passing HCAPTCHA to change the proxy. 
This code will return the current IP:
```
 ip = requests.get('https://api.ipify.org').text
 print("new ip:", ip)
```
![image](https://user-images.githubusercontent.com/24871064/182663264-80313e73-222e-465d-b32a-0b1c395c9e87.png)

**Comment by kuuyby9duoi** [comment]
> ## Tip to bypass IP limitation
> Well I currently work with a residential proxy, whose connection model is as follows:
> 
> ```gfm
> user:password@54.236.156.20:31112
> ```
> 
> I would like to know how to insert the use of proxy in your project to be able to circumvent possible limitations by IP

I don't know anything about Python but the way I break the code is very good.
I have added src\apis\challenge.py right after the first try of the loop to change the proxy before starting a Captcha Session. You can also add to after line _if resp == challenger.CHALLENGE_SUCCESS:_   or _def is_successful_at_the_demo_site():_ At Sevices\hcaptcha_challenger\core.py this applies to after passing HCAPTCHA to change the proxy. 
This code will return the current IP:
```
 ip = requests.get('https://api.ipify.org').text
 print("new ip:", ip)
```
![image](https://user-images.githubusercontent.com/24871064/182663264-80313e73-222e-465d-b32a-0b1c395c9e87.png)
