### ISSUE TITLE
[Challenge] parrot

### ISSUE THREAD

**Issue by liuming9157** [QIN2DIM/hcaptcha-challenger#112]
### Prompt[en]

Please click each image containing a parrot

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=

### Screenshot of the challenge

I find a new prompt of parrot and get the model through the framework of  hcaptcha-model-factory. It works well in test. I can upload if you need it.

**Comment by QIN2DIM** [comment]
dup of #102

**Comment by liuming9157** [comment]
yeah,but I don't find it in your released model.I can add it if you like

**Comment by QIN2DIM** [comment]
我发现目前的社区模式不太友好，普通访客貌似没有权限 push release。如果您那边训练了新的模型- -在代码中的改动似乎只需要修改 `objects.yaml`

**Comment by QIN2DIM** [comment]
可以提个PR
