### ISSUE TITLE
[Challenge] dog with a collar on its neck

### ISSUE THREAD

**Issue by huozhenlin** [QIN2DIM/hcaptcha-challenger#113]
### Prompt[en]

Please click each image containing a dog with a collar on its neck

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/19356940/182335139-8f387771-6481-430b-89f1-92d514844e74.png)

**Comment by liuming9157** [comment]
I trained and get the mode successfuly. If anybody want it just contact me.My email is liuming@mzsat.cn.BTW,I am taining the prompt of dog with closed eyes but the value rate is low.If anybody has the ready-to-use model of dog with closed eyes, contact me too.

**Comment by Vinyzu** [comment]
Any updates on this? getting this alot recently

**Comment by ndtrongvn** [comment]
> Any updates on this? getting this alot recently

Yeah, me too
