### ISSUE TITLE
[Question]  Hcaptcha Bypass using AI

### ISSUE THREAD

**Issue by ProHaxProHax** [QIN2DIM/hcaptcha-challenger#114]
How to Modify this Source Code to make it only solve hCaptchas for "Discord.com" for example and return the hCaptcha G Response Token for another Programm to Loop tought it using Proxies for example.

Just get the Token back and send it over to another Software is this possible? Because then we could open 50 Tabs for example -> Auto solving hCaptchas and send the Tokens Over to other Software that runs on Requests + Proxies for faster Usage.

Please everyone wants this.

**Comment by QIN2DIM** [comment]
Are you a student?
