### ISSUE TITLE
[Challenge] dog without a collar

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#115]
### Prompt[en]

Please click each image containing a dog without a сollar

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

<img width="40%" src="https://user-images.githubusercontent.com/62018067/182604801-01f68c5f-35a9-4984-8c4a-a7d6352fb908.png">

**Comment by bitcoinautomatic** [comment]
> ### Prompt[en]
> Please click each image containing a dog without a сollar
> 
> ### New types of challenge
> New prompt (for ex. Please select all the 45th President of the US)
> 
> ### Sitekey
> https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7
> 
> ### Sitelink
> https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7
> 
> ### Screenshot of the challenge
> ![image](https://user-images.githubusercontent.com/62018067/182604801-01f68c5f-35a9-4984-8c4a-a7d6352fb908.png)

will new tasks with dogs be added to your script?

**Comment by QIN2DIM** [comment]
- #113
