### ISSUE TITLE
Seperate solution

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#122]
Hi,
I respect your work and know how much it is useful, but I can't integrate it with my python code
I want you to give a standard onnx format model so that everyone like me can make prediction and use it anyway wanted maybe for even classification task
Does all predictions made by yolov6? And why don't you use yolov7 as it is fast
Can you give links about guide on how did you actually trained the model for custom classification like dog_with_open_eyes
I also want to use it to solve recaptcha
Basically, I am making a pypi version of library that can handle every captcha with single line like this
```
solver = CaptchaSolver().setCaptchaTypeAs#anylikehcaptcha.solve()
```
I actually got success with very good accuracy using efficientnet before but it can't predict new classes that hcaptcha made recently
Also, I have solved too many classes of recaptcha, text captcha, upside down captcha, duplicate image finder captcha, slide captcha, and many more, generally 9 types supported by it
I want you to contribute in it by giving me and teaching me how to do custom classification task, dataset length required for it and give me yolov6 in h5 or onnx format
Thanks

**Comment by M-Zubair10** [comment]
After I get image what should I call to predict class?

**Comment by beiyuouo** [comment]
For custom classification task you can get the model structure and train process at [here](https://github.com/beiyuouo/hcaptcha-model-factory). According to my experience, the required size of the dataset depends on the difficulty of the task. If it is a more general classification, 200 may be enough (such as dog vs cat), and if it is a fine-grained classification (such as dog with open eyes), it may need more than 500.

**Comment by M-Zubair10** [comment]
Since you have predicted too many classes, I want to use your model
```
# Fill this function
def predict(img:ndarray, obj:str):
     """
     suppose obj is dog_with_closed_eyes
     """
   pass

**Comment by M-Zubair10** [comment]
Can you provide an example on how did you train the model
Do I need to train it on 2 classes and use seperate models?
Appreciate it.

**Comment by M-Zubair10** [comment]
Can you provide a link to resnet model?

**Comment by QIN2DIM** [comment]
https://github.com/beiyuouo/hcaptcha-model-factory

**Comment by M-Zubair10** [comment]
Can you guide me to classify class,
As seen, it looks like I need to do binary image classification right? and then use the right model according to the given title in hcaptcha
Hmm, cool thanks anyway!
You already covered almost all the types

**Comment by M-Zubair10** [comment]
Thats too much easy, I just read the wiki guide, I actually used tensorflow but here, everything is preprocessed thanks again!
Now I can solve recaptcha all classes

**Comment by QIN2DIM** [comment]
I've been so busy lately that I haven't had much time to follow hcaptcha-challenger. I haven't updated the technical documentation for a long time.

In this project, all models are trained automatically.

**Comment by winktool** [comment]
> 

Could you share your code about solving reCaptcha?
