### ISSUE TITLE
[Question] Why not using CLIP. Clip can also solve recaptcha-v2! 

### ISSUE THREAD

**Issue by EdwardArthurKane** [QIN2DIM/hcaptcha-challenger#126]
https://colab.research.google.com/github/kevinzakka/clip_playground/blob/main/CLIP_reCAPTCHA.ipynb

(Note that its a demo, and its only working on sites that allow the fallback to be used in their recaptcha challenge which I think its set to NO by defulat'e )

**Comment by QIN2DIM** [comment]
The reCAPTCHA v2 challenge requires a higher model accuracy rate, but I have that planned.🥊

**Comment by sneedgers** [comment]
> 

![image](https://user-images.githubusercontent.com/107140768/183900721-2865c2d9-88fa-4baf-a3c0-a4cf2c6a1ba3.png)
Your bot is amazing thank you <3

**Comment by M-Zubair10** [comment]
Does CLIP always solve recaptcha???
What's the success rate, that's sounds great?
