### ISSUE TITLE
[Challenge] lion with an open mouth

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#127]
### Prompt[en]

Please click each image containing a lion with an open mouth.
请单击每个包含张开嘴的狮子的图像。

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=c86d730b-300a-444c-a8c5-5312e7a93628

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=c86d730b-300a-444c-a8c5-5312e7a93628

### Screenshot of the challenge

![QmhvgK8J5F](https://user-images.githubusercontent.com/62018067/183987150-4fd78cc5-454b-4575-8d47-39be3bbb8b99.jpg)

**Comment by M-Zubair10** [comment]
is it open for contribution?
Can I made a  model for it?
I am very expert in data annotation and do it in very little time generally 5k+ images a day

**Comment by searchingforcode** [comment]
> is it open for contribution? Can I made a model for it? I am very expert in data annotation and do it in very little time generally 5k+ images a day

Same question
