### ISSUE TITLE
[Challenge] female lion

### ISSUE THREAD

**Issue by huozhenlin** [QIN2DIM/hcaptcha-challenger#128]
### Prompt[en]

请点击每张包含雌狮的图片。
Please click each image containing a female lion.

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/19356940/184092787-6ee23998-58b8-4dad-abaa-7e626d9a39f5.png)

**Comment by QIN2DIM** [comment]
![Suggestion](https://user-images.githubusercontent.com/62018067/184101876-eb212676-95ce-4c06-aa03-c64b92db5891.gif)

**Comment by Vinyzu** [comment]
Isnt this LionWithAMane in "Reverse"?
