### ISSUE TITLE
[Question] What are different versions of yolo and what is the function of resnet model?

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#129]
I want to know, what are different yolo versions?
which is best?
what is the purpose of resnet model?
what classes resnet predict?

**Comment by QIN2DIM** [comment]
> what are different yolo versions?
https://github.com/meituan/YOLOv6
https://github.com/ultralytics/yolov5

> which is best?
I don't know

> what is the purpose of resnet model?
Image classification

> what classes resnet predict?
https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/objects.yaml
