### ISSUE TITLE
onnx model always give postive and negative value, which to choose?

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#130]
![image](https://user-images.githubusercontent.com/47709300/184119781-5cbe0482-34e2-4067-8be8-312c551ae175.png)
I used it using onnxruntime 
Why it predict wrong, which is considered to be true (label) and which to false

**Comment by QIN2DIM** [comment]
You can check the source code, I don't understand what you are asking.👀

**Comment by M-Zubair10** [comment]
Can you please show me what did you do after getting image screenshot?
To predict classes
I find it hard reading your source code, its too long
