### ISSUE TITLE
[Question] How to make prediction

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#131]
Ok listen now, I have my own chromedriver, my own label name, my own image, all I wanted to know is to get a function like this
```
res = predict(model, img, label)
print(res)
>>> True or False 
```
Means that image matches or not

How I can choose model
Your source code is very long, I'm reading since morning and still no luck

Just give two functions
```
def auto_choose_mode() -> model:
    pass
def predict() ->bool:
    pass

```

**Comment by beiyuouo** [comment]
If you really don't want to read any code, I recommend you to use the free api @captcha-challenger.
The document at: https://captcha-challenger.github.io/docs/#/hcaptcha/

**Comment by M-Zubair10** [comment]
ok let me see

**Comment by M-Zubair10** [comment]
What is rainbow.yaml?

**Comment by M-Zubair10** [comment]
Fine I get the prediction required thanks anyway
By the way, what is rainbow.yaml

**Comment by QIN2DIM** [comment]
The answers to the questions you asked over the past two days are all reflected in the same python file, which is just 50 lines of code in total.

Only the models registered in [objects.yaml](https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/objects.yaml) will be downloaded automatically.
https://github.com/QIN2DIM/hcaptcha-challenger/blob/28eb0767a8432cb28ec4cc743af4e569e5385d54/src/services/hcaptcha_challenger/solutions/resnet.py#L157-L179
