### ISSUE TITLE
[Question] Elephant and bird

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#133]
I get a challenge with label click each image with elephant but it not included in onnx models, train it please
And for bird, I think parrot.onnx will work let me try it

**Comment by QIN2DIM** [comment]
https://github.com/QIN2DIM/hcaptcha-challenger/blob/28eb0767a8432cb28ec4cc743af4e569e5385d54/src/services/hcaptcha_challenger/solutions/yolo.py#L18
