### ISSUE TITLE
[Question] Smiling dog always fail, retrain it

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#134]
I tried many times, but always smiling dog fail

**Comment by M-Zubair10** [comment]
Thanks for your help!, I really appreciate it
Can you please provide me dataset labelled so that I can extend it and retrain on some bad classes

**Comment by M-Zubair10** [comment]
Which horse is better? Resnet or Yolo?

**Comment by QIN2DIM** [comment]
> Smiling dog always fail

truly. I think it was a failure, I had a problem with the labeling, I didn't know how to tell that the dog was smiling, did it just open its mouth?

I feel that some kinds of dogs are so cute that I think they are smiling even when they are expressionless.

It would be easy to define "smile" simply by whether or not the mouth is open.

**Comment by QIN2DIM** [comment]
- #157
