### ISSUE TITLE
[Question] Hcaptcha took so long to load that causes auto reload after 8 seconds

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#135]
Hcaptcha loading widget continues and load after too much time, generally changing 8 seconds to 60 solved it but I wanted to know why it happen?

**Comment by QIN2DIM** [comment]
The network speed is not fast enough. If a proxy is used, it is also possible that the threat level of the proxy is high. There are also a few cases of HCAPTCHA's busy interface.

**Comment by M-Zubair10** [comment]
Did you solved the area select prompt
Can i use model factory for recaptcha classification?
