### ISSUE TITLE
[Challenge] horse with white legs

### ISSUE THREAD

**Issue by huozhenlin** [QIN2DIM/hcaptcha-challenger#138]
### Prompt[en]

请单击每个包含白腿马的图像。
Please click each image containing a horse with white legs.

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/19356940/185353176-6ac0a3d4-a764-4869-b37b-c1d9b6785fc1.png)

**Comment by QIN2DIM** [comment]
白腿马
