### ISSUE TITLE
[ERROR] ONNX-Import Assertion Failed

### ISSUE THREAD

**Issue by Vinyzu** [QIN2DIM/hcaptcha-challenger#140]
Note: This is an error i got which is from my implementation of the ai.

```
  File "C:\Bot\dislock\main.py", line 411, in captcha_solver
    self.challenger = ArmorCaptcha(dir_workspace=DIR_CHALLENGE, dir_model=DIR_MODEL, lang='en', debug=True,
  File "C:\Bot\dislock\hcaptcha_challenger\core.py", line 126, in __init__
    self.pluggable_onnx_models = self.pom_handler.overload(
  File "C:\Bot\dislock\hcaptcha_challenger\solutions\resnet.py", line 203, in overload
    return {
  File "C:\Bot\dislock\hcaptcha_challenger\solutions\resnet.py", line 204, in <dictcomp>
    finger: FingersOfTheGolderOrder(finger, dir_model, path_rainbow)
  File "C:\Bot\dislock\hcaptcha_challenger\solutions\resnet.py", line 93, in __init__
    super().__init__(onnx_prefix, f"{onnx_prefix}(ResNet)_model", dir_model, path_rainbow)
  File "C:\Bot\dislock\hcaptcha_challenger\solutions\resnet.py", line 41, in __init__
    self.net = cv2.dnn.readNetFromONNX(self.onnx_model["path"])
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:709: error: (-215:Assertion failed) model_proto.has_graph() in function 'cv::dnn::dnn4_v20211220::ONNXImporter::populateNet'
```

Source: https://github.com/Vinyzu/DiscordGenerator/blob/main/main.py#L411

**Comment by Vinyzu** [comment]
The Question Label was Giraffe.

**Comment by Vinyzu** [comment]
Update: Other Question are also affected

Also replica of [#54](https://github.com/QIN2DIM/hcaptcha-challenger/issues/54)

**Comment by QIN2DIM** [comment]
Are you downloading models in a parallel tasks?

**Comment by Vinyzu** [comment]
> Are you downloading models in a parallel tasks?

Possibly yes,
But i have reports of manually downloading in from ur modelhub and getting the same error...

**Comment by QIN2DIM** [comment]
You can use the `install` command to download the model in advance, but if that still causes problems, the scenario is more complicated.

**Comment by Vinyzu** [comment]
https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/apis/scaffold/install.py#L42

Right? Ill check it out!

**Comment by QIN2DIM** [comment]
```python
import os
from typing import Optional
from urllib.request import getproxies

import requests


def download_model_(
        dir_model, path_model, model_src, model_name, upgrade: Optional[bool] = None
):
    os.makedirs(dir_model, exist_ok=True)

    if os.path.exists(path_model) and not bool(upgrade):
        return
    if not model_src.lower().startswith("http"):
        raise ValueError

    print(f"Downloading {model_name} from {model_src}")
    with requests.get(model_src, stream=True, proxies=getproxies()) as response, open(path_model, "wb") as file:
        for chunk in response.iter_content(chunk_size=1024):
            file.write(chunk)

```

**Comment by Vinyzu** [comment]
Yes thats what i linked, thanks ill check if it works

**Comment by Vinyzu** [comment]
Update:
it appears to be a httpx flaw. I changed the request downloading code of your repo to httpx, to use less imports
(https://github.com/Vinyzu/DiscordGenerator/blob/a74847202420ad18ac65d2ed797d2d194a6f06b5/hcaptcha_challenger/solutions/kernel.py#L100)
Httpx is for some reason broken and when streaming a request it doesnt give any output.

**Comment by QIN2DIM** [comment]
Do not download the model concurrently, as the associated files are placed on GitHub and your requests will be limited and the downloaded model file may be corrupted.

**Comment by QIN2DIM** [comment]
Just GET directly, no need to stream. It is very tiny
