### ISSUE TITLE
[Invalid] Set `ChromeOptions()` | proxy

### ISSUE THREAD

**Issue by JokersCat** [QIN2DIM/hcaptcha-challenger#15]
Hey , 
So will there come a proxy option so that you can run the driver with a attachet proxy?

**Comment by QIN2DIM** [comment]
You can describe the application in more detail.

**Comment by JokersCat** [comment]
Yeah so. Could you add a option to use a Proxy for the opened window?

**Comment by QIN2DIM** [comment]
I don't understand what you mean…

**Comment by QIN2DIM** [comment]
Why do I fall in the rate limiting? Why do I need a proxy?

**Comment by JokersCat** [comment]
I mean when I fill in informations on a website and then use your Programm to solve the captcha 1 Account gets created. But after that you have an cooldown. And to bypass that you would need a different Ip. So i would need a Setting in the Programm to add a proxy server

**Comment by QIN2DIM** [comment]
> But after that you have an cooldown. And to bypass that you would need a different Ip.

?🌚

**Comment by JokersCat** [comment]
Kinda I guess so basically a support for proxies but I think I can manage that myself when I think about it 😅

**Comment by QIN2DIM** [comment]
- https://github.com/QIN2DIM/hcaptcha-challenger/issues/4

If you want to use `hcaptcha-challenger` in your own project I think you should know how to do it, I probably can't help you.🤷‍♀️

**Comment by JokersCat** [comment]
Yeah I looked more into it and now understand how I can use it 😊
