### ISSUE TITLE
feat(todo): re-train model

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#157]
In extreme tests, the effect of the following model does not meet the expectations, and we plan to release them in the future.
- [ ] living_room
- [x] bedroom
- [ ] smiling_dog
- [x] conference_room

**Comment by M-Zubair10** [comment]
Did it updated?
How will I know that project is updated? and download new models object.yaml automatically, currently I do manually

**Comment by QIN2DIM** [comment]
emmm... Let me show you a sketch I made earlier.😂

![未命名绘图](https://user-images.githubusercontent.com/62018067/188775304-7f68d161-6c44-4b75-9f6f-7332a4f86f8f.png)

**Comment by QIN2DIM** [comment]
For the tags in objects.yaml, Challenger maintains an Assets object that will help you automatically update and replace the model (file of the same name) and automatically download missing models locally as the challenge progresses. You do not need to download all ONNX models from Releases in advance.

**Comment by QIN2DIM** [comment]
And for the backward case of content in 'objects.yaml', I haven't done it yet.

**Comment by M-Zubair10** [comment]
These labels now came rarely, they are updating constantly new prompts, currently bottle broken is hot one
Did you solve the fit bounding box around object prompt you said you have solved it gracefully, can you show it

**Comment by M-Zubair10** [comment]
Can you train object tractor for me? its the only object left for recaptcha solver

**Comment by 2xmonth** [comment]
> Can you train object tractor for me? its the only object left for recaptcha solver

This doesn't have to do with hcaptcha but if you need to train a object detection model on the recaptcha tractors what you can do is just use images of tractors on google and then train it on those. Or if you don't want to do any of that just use a audio solver

**Comment by QIN2DIM** [comment]
Yes, it's as easy as homework.😂

**Comment by M-Zubair10** [comment]
I'll definitely try it out soon
