### ISSUE TITLE
[Challenge] Cat long hair/short hair

### ISSUE THREAD

**Issue by Tainted06** [QIN2DIM/hcaptcha-challenger#167]
### Prompt[en]

Please click each image containing a cat with long hair. Please click each image containing a cat with short hair.

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

**Long Hair:**
![UgGsDO5P](https://user-images.githubusercontent.com/80160851/187828834-5f5ad7b6-8701-48b1-9655-b1d6061b79dd.png)

**Short Hair:**
![xAa8bGwV](https://user-images.githubusercontent.com/80160851/187828862-688a5d62-f032-4ef7-9c3b-92452f91be26.png)

**Comment by QIN2DIM** [comment]
- #159
