### ISSUE TITLE
feat(pending): New `vertical river` challenge

### ISSUE THREAD

**Issue by tsothcott** [QIN2DIM/hcaptcha-challenger#17]
Hi!

I have noticed some additional River images in recent days, and the solution is providing false positives.

I have attached a ZIP with some examples. The images in the attached ZIP are being identified as 'vertical' when they are in fact, not.

Thanks for this project!

[river_false_positives.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/8225691/river_false_positives.zip)

**Comment by QIN2DIM** [comment]
Thank you for your issue!

I looked at the sample images you provided and it's just crazy!

I'm not sure if hcaptcha's development team noticed our work, But I'm sure these generated images are deliberately avoiding SK-IMAGE's feature engineering.

**Comment by QIN2DIM** [comment]
I would like to ask exactly which site these images appear in the challenge.

**Comment by tsothcott** [comment]
It seems that the images got harder when there was heavy usage. Anyway, here is the sitekey and host:

"hostname": "https://mobile.api.prod.veve.me",
"sitekey": "86c60170-2a73-489f-89ad-fca627914423",
