### ISSUE TITLE
[Question] Another languages? Golang/Node

### ISSUE THREAD

**Issue by wireguard-dev** [QIN2DIM/hcaptcha-challenger#175]
It would be nice to transfer (fork) the project to other languages.

**Comment by QIN2DIM** [comment]
not easy

**Comment by QIN2DIM** [comment]
I have made technical selection during the project. I think Python is the best practice. But if you have other special needs, you can try migration.

**Comment by QIN2DIM** [comment]
(Rewriting this project in another language is a bit challenging for me, and I don't have much time for that at the moment.

**Comment by ItsCEED** [comment]
You can still use it as an API so you have a way of integrating it into another project that uses other language, rewriting it at this point is kinda useless (yet?)
