### ISSUE TITLE
[Challenge] plant hanging from the ceiling

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#184]
### Prompt[en]

Please click each image containing a plant hanging from the ceiling

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

![img_v2_30e55665-e7f5-4264-a517-688a0ccfd44g](https://user-images.githubusercontent.com/62018067/189140130-e256ea52-3fda-493e-9b6f-d72d2518c8ca.png)

**Comment by ninjadoc107** [comment]
because so much new captcha, every day a new one

> ### Prompt[en]
> Please click each image containing a plant hanging from the ceiling
> 
> ### New types of challenge
> New prompt (for ex. Please select all the 45th President of the US)
> 
> ### Sitekey
> https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09
> 
> ### Sitelink
> https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09
> 
> ### Screenshot of the challenge
> ![img_v2_30e55665-e7f5-4264-a517-688a0ccfd44g](https://user-images.githubusercontent.com/62018067/189140130-e256ea52-3fda-493e-9b6f-d72d2518c8ca.png)

because so much new captcha, every day a new one

**Comment by ItsCEED** [comment]
haven't seen the challenge in the last 24 hours, did they replace it with #187?

**Comment by QIN2DIM** [comment]
@ninjadoc107 boring game... Challenger's monitoring, dataset building, annotation, model training, export, and delivery are almost fully automated workflows that allow us to deliver solutions to new challenges in less than an hour
