### ISSUE TITLE
[Question] Looking for an easy way to implement this solver in any script.

### ISSUE THREAD

**Issue by maximedrn** [QIN2DIM/hcaptcha-challenger#185]
Hello @QIN2DIM,
_(Thank you for you script and my credits 😉)_

As the title says, I _(someone I know)_ would like to know how to **add this to any Python script**.
For example, if I'm automating a website and I want to resolve an hCaptcha, what lines of code should I add to resolve it?

```python
# Selenium imports...


def main() -> None:
    """Main function as example."""
    web = webdriver()  # Open and get the instance of the webdriver.
    # I do my work on any website.
    # Solve the hCaptcha, example:
    from hcaptcha_challenger import hCaptcha
    hcaptcha = hCaptcha(webdriver_instance=web)
    hcaptcha.solve()
    web.close()


if __name__ == '__main__':
    main()
```

**Comment by ItsCEED** [comment]
You can look up @Vinyzu solution on that here https://github.com/Vinyzu/DiscordGenerator/blob/main/main.py

Pretty neat job

**Comment by maximedrn** [comment]
Thank you @ItsCEED 👌
