### ISSUE TITLE
How to run on specified site 

### ISSUE THREAD

**Issue by jankiki87** [QIN2DIM/hcaptcha-challenger#191]
How to run this solver on specified site on only solve hcaptha ???

**Comment by jankiki87** [comment]
![Przechwytywanie (1)](https://user-images.githubusercontent.com/112200369/189742181-1d8b8ec5-51de-4a36-ac15-a485de7349fb.png)
 i want to only solve on site how to ????

**Comment by ItsCEED** [comment]
You need to modify it to fit it in your script, its not like you just wanna solve and do nothing?
