### ISSUE TITLE
feat(add): Allow to change Language

### ISSUE THREAD

**Issue by skrrppop** [QIN2DIM/hcaptcha-challenger#2]
It doesnt work when changing chrome language to english
and changing get_labels to return label in english
But the image classifier just takes chinese

**Comment by QIN2DIM** [comment]
I am trying to edit the tag mapping.I didn't think anyone would pay attention to the project.(/▽＼)

**Comment by QIN2DIM** [comment]
However, from the conclusion of my research, this `i18n` compatibility is not an easy job.

On a **PC**, hCaptcha determines what language to use based on the browser's startup parameters, and on **Linux** it is based on the session window's `locale` environment variable.

---

In addition, the tags given by hCaptcha may not be in the standard encoding format.You can run the following code in your favorite Python IDE, which is a very clever trick I found while researching how hCaptcha works.

```python
print("AWESΟME" == "AWESOME")
print("bіcycle" == "bicycle")

```

**Comment by saitishmukhametov** [comment]
just change label_aliases and get_label function, since in my (russian) language we have different word endings u have to consider it into label_aliases. 
worked perfectly fine for me
```
        try:
            _label = label_obj.text.split('с ')[1]
        except (AttributeError, IndexError):
```
```
        self.label_alias = {
            "велосипедами": "bicycle",
            "поездами": "train",
            "грузовиками": "truck",
            "автобусами": "bus",
            "автобусами": "bus",
            "самолетами": "aeroplane",
            "лодками": "boat",
            "лодками": "boat",
            "машинами": "car",
            "мотоциклами": "motorbike",
        }
```

**Comment by QIN2DIM** [comment]
Are you running on Linux? 👀

**Comment by saitishmukhametov** [comment]
nope

**Comment by QIN2DIM** [comment]
Yes, this does solve the problem.

But I'm looking for a way to automatically adapt to the language and match the corresponding splitting function to the `locale` environment variable.This doesn't look easy

**Comment by QIN2DIM** [comment]
> nope

 Did you comment out this line of code? 👀

https://github.com/QIN2DIM/hcaptcha-challenger/blob/1bc20e29d8eb91645f8c7ef0276adbf53c4042d4/src/services/utils/toolbox/toolbox.py#L58

**Comment by QIN2DIM** [comment]
Okay, I know how to fix this problem....Just read the environment variables directly - -

**Comment by saitishmukhametov** [comment]
the problem is, that some sites force language on hcaptcha, yes i did comment the lang stuff
greasyfork hcaptcha solver script solves this problem by uploading target image to wolframimage or something like this, where they get keywords and then compare them with long list of built-in keywords

**Comment by QIN2DIM** [comment]
> stuff

The solution you propose seems to be quite time consuming. Note that the `hCaptcha challenge` has a time limit of roughly 100 seconds, and the page element will reset after that timeout. 

> force language

Yes, like EPIC login, they remove the checkbox and lock the element language.

**Comment by QIN2DIM** [comment]
我已经在测试用例中统一了挑战语言，在主流的操作系统上都可以生效。关于你说的挑战语言锁定的情况，可否提供一些测试站点。

**Comment by skrrppop** [comment]
Hey what i meant is when changing Language  the label doesnt  get recognized.
And if u try to translate it with using self.label_alias not all aliases are included or correct
Do you understand what i mean?
And thanks for youre project i learned alot with it

**Comment by QIN2DIM** [comment]
> Hey what i meant is when changing Language the label doesnt get recognized.

So won't it be possible to identify accurately after the language is unified? 👀

> And if u try to translate it with using self.label_alias not all aliases are included or correct

I don't quite understand the exact meaning of the phrase

**Comment by skrrppop** [comment]
I mean when ur getting the label when its in english and than using `self.label_alias` to get the correspondend chinese word so u can pass it to the image classificator . 
It turned out that aeroplane in english is airplane on the label text

**Comment by QIN2DIM** [comment]
I still don't understand what you mean...🤦‍♂️

**Comment by QIN2DIM** [comment]
Oh, my God, there are three people talking in here, out of context!

Anyway. I've just thought of a more adventurous way to unify labels in all languages.

**Comment by skrrppop** [comment]
> I still don't understand what you mean...🤦‍♂️
> 
> I think you may not be reading the purpose of this variable. I have mentioned above. The purpose of self.label_alias is not to translate, but to correct miscoding.

Ah im an idiot . But when im trying to use an english label for example like 'train' for _label it doesnt work .

Image

![Screenshot_1](https://user-images.githubusercontent.com/85704413/155014447-f17a30df-5330-4381-ab90-3efbbf3e18e8.png)
)

**Comment by QIN2DIM** [comment]
WHAT! What did you do with the source code. 😂😂😂😂

**Comment by QIN2DIM** [comment]
Ultimately, I think it's a **pseudo-need**. I don't think it should matter what language is used to open the challenge.

If you do have to start a challenge in a particular language for some indescribable reason, you can refer to this friend's approach and write your own **splitting methods** as well as `label alias`.

**Comment by skrrppop** [comment]
if i use `_label = label_obj.text.split()[-1]` i get the correct label but the programm doesnt work and the tactical_retreat function retuns True

**Comment by QIN2DIM** [comment]
That's because you didn't add the cleansed noun to the `self.label_alias`.
