### ISSUE TITLE
[Invalid] KeyError

### ISSUE THREAD

**Issue by henzycuong1** [QIN2DIM/hcaptcha-challenger#20]
Hi, I got a issue at line "model.solution(img_stream=data, label=self.label_alias[self.label])". It raised a exception with args is "KeyError:'train'". What is it mean ?

**Comment by QIN2DIM** [comment]
I do not know

**Comment by QIN2DIM** [comment]
If you are running the code I provided, the `KeyError` is an unlikely error to be reported.
