### ISSUE TITLE
[Challenge] rabbit

### ISSUE THREAD

**Issue by luanon404** [QIN2DIM/hcaptcha-challenger#203]
### Prompt[en]

 Please click each image containing a rabbit

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

9a5da798-adac-4c50-9c7e-79d9f92bd4c0

### Sitelink

maximedrn.github.io

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/71830807/191020360-490fb2fd-679b-433b-b8c3-1cfa1f948686.png)

**Comment by luanon404** [comment]
can i train onnx with https://github.com/beiyuouo/hcaptcha-model-factory module?

**Comment by QIN2DIM** [comment]
> can i train onnx with https://github.com/beiyuouo/hcaptcha-model-factory module?

o_o .... yes, you can.

**Comment by luanon404** [comment]
> > can i train onnx with https://github.com/beiyuouo/hcaptcha-model-factory module?
> 
> o_o .... yes, you can.

hmm... thanks, one more can you tell me what the rainbow.yaml file is used for? I see all returns as None not True or False, and do i need to retrain some onnx file? some of them seem to be not working well (unrecognizable) ex: teacup_with_similar_porcelain_design_pattern.onnx

**Comment by QIN2DIM** [comment]
@luanon404 

**Rainbow** is a deprecated feature, hCAPTCHA team now uses GAN to generate stable images, and they rotate the dataset every once in a while.

> I see all returns as None not True or False, and do i need to retrain some onnx file? some of them seem to be not working well (unrecognizable) ex: teacup_with_similar_porcelain_design_pattern.onnx

WE can go to the discussions of another project. 🦉 You can provide more information

**Comment by luanon404** [comment]
> WE can go to the discussions of another project. 🦉 You can provide more information

its very hard with me :), i just used your onnx module to be a hcaptcha solver using requests module, but after i looked through your code it seems you have a lot of duplicate code, resnet.py after i cleaned it up, it only 12 lines left xD

**Comment by luanon404** [comment]
turtle_under_the_water this is different with turtle on grass

**Comment by QIN2DIM** [comment]
??

**Comment by luanon404** [comment]
label: rabbit
failed at this image
![image](https://user-images.githubusercontent.com/71830807/191070945-818d3de4-ae51-4d3f-9677-bbecc88ab164.png)
