### ISSUE TITLE
[Question] Hi, How to use hcaptcha-challenger

### ISSUE THREAD

**Issue by pgshow** [QIN2DIM/hcaptcha-challenger#204]
## Brief description

I just find this project, it's a great AI library, but there has no instruction, Can I know how to use it?

**Comment by geckoy** [comment]
same here ! please can you provide us with brief instruction

**Comment by pgshow** [comment]
能大概介绍下吗，没有找到使用说明

**Comment by QIN2DIM** [comment]
You can find the steps to run the demo program in the[ wiki](https://github.com/QIN2DIM/hcaptcha-challenger/wiki).

But I'm sure that's not what you're asking.

**Comment by QIN2DIM** [comment]
#226
