### ISSUE TITLE
WARN: Browser extension is a trap 🚳

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#206]
If you intend to use the Challenger to create a browser extension to handle human-machine challenges(hCAPTCHA), best practice is to distribute pluggable models to clients on demand and perform prediction tasks based on client-side computing power, rather than downloading models to your server and providing a paid subscription interface to unsuspecting users.

People who do this treat me and your users like idiots. 🚳

I considered making browser extensions and APIs a long time ago, but these plans would have distracted me, so I had to alert some people as much as I could. 😂

**Comment by QIN2DIM** [comment]
If anyone needs a free Challenger Browser extension, please leave a comment here and if the project has more than 1k stars, I will start the project. I guarantee this extension will be free forever (Only Binary-Classification).

In my ideas, this will be an AI model running on the client, and you do not need to rely on any cloud -based interface.

**Comment by liuming9157** [comment]
I think this is a good idea.

**Comment by devnullone** [comment]
> Si quelqu’un a besoin d’une **extension gratuite du navigateur Challenger**, veuillez laisser un commentaire ici et si le projet a plus de 1k étoiles, je ferai la promotion de ce plan. Je vous garantis que cette extension sera gratuite pour toujours (uniquement Binary-Classification).
> 
> Dans mes idées, il s’agira d’un modèle d’IA fonctionnant sur le client, et vous n’avez pas besoin de compter sur une interface basée sur le cloud.

That is awesome!

**Comment by khalidwaleed0** [comment]
> If anyone needs a **free Challenger Browser extension**, please leave a comment here and if the project has more than 1k stars, I will promote this plan. I guarantee this extension will be free forever (Only Binary-Classification).
> 
> In my ideas, this will be an AI model running on the client, and you do not need to rely on any cloud-based interface.

This will be awesome

**Comment by Marshall-67** [comment]
would be awesome

**Comment by cintagram** [comment]
awesome :)

**Comment by Wikidepia** [comment]
Hi, I created a Chrome extension based on the hcaptcha-challenger model, which you can find here: https://github.com/Wikidepia/hektCaptcha-extension

It is still in development, but you can try the first release in the releases section.

**Comment by wanghaisheng** [comment]
**In my ideas, this will be an AI model running on the client, and you do not need to rely on any cloud-based interface.**
this is great idea
