### ISSUE TITLE
[Question] Isn't it better to load model according to label 

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#209]
Since hcaptcha is updating labels continuosly, I think it will be useful to load model according to given label
This will reduce memory consumption

**Comment by QIN2DIM** [comment]
emmmm.....wait

**Comment by M-Zubair10** [comment]
I already did it in my project, but I'm suggesting there could be a --memory-optimized argument
I'm just suggesting, to load model according to label, it takes about 0.5s right?

**Comment by QIN2DIM** [comment]
In fact, I did this at first. I later changed it to a one -time load. On the other hand, these models are very small in size, and the long-term loss is not high.

It is a good idea to control different model initialization behaviors through parameters. I'll add it in a future release.
