### ISSUE TITLE
[Question] `seaplane` challenge | EN | 

### ISSUE THREAD

**Issue by xBytez5636** [QIN2DIM/hcaptcha-challenger#22]
2022-03-22 03:55:45 | DEBUG - >> Challenge [ArmorCaptcha] Avoiding the unmanageable challenge - label=seaplane

hCaptcha updated new images "seaplane" how can I manually add this?

**Comment by QIN2DIM** [comment]
Duplicate of 
- https://github.com/QIN2DIM/hcaptcha-challenger/issues/10

**Comment by QIN2DIM** [comment]
I will re-add this feature, but the time is not right yet.
