### ISSUE TITLE
[Question] how to get as many pictures challenge?

### ISSUE THREAD

**Issue by luanon404** [QIN2DIM/hcaptcha-challenger#227]
If i know the site key can i get many pictures to train?
I have tried many times but it is very difficult to get many pictures, at most 80 ~ 100 pictures per 1000 times.
Is there any way to get the exact picture i need?

**Comment by QIN2DIM** [comment]
> at most 80 ~ 100 pictures per 1000 times.

Are you serious😂

**Comment by luanon404** [comment]
> > at most 80 ~ 100 pictures per 1000 times.
> 
> Are you serious😂

yes I having about 100k underwater turtle photos now

**Comment by luanon404** [comment]
I use requests to pass hcaptcha so it's normal

**Comment by QIN2DIM** [comment]
<img width="35%" src="https://user-images.githubusercontent.com/62018067/192089134-9e1fb442-735c-4322-a9e1-dc0a8321c7e3.jpg">

**Comment by luanon404** [comment]
> <img alt="" width="35%" src="https://user-images.githubusercontent.com/62018067/192089134-9e1fb442-735c-4322-a9e1-dc0a8321c7e3.jpg">

Is there any way to get the exact picture i need? i really need it

**Comment by QIN2DIM** [comment]
？？？？？
How many images do you think you need to train the model, I feel that a few hundred is enough. If it is learning with fewer samples(few-shot learning), it is even possible to learn while challenging.

**Comment by luanon404** [comment]
> ？？？？？ How many images do you think you need to train the model, I feel that a few hundred is enough. If it is learning with fewer samples(few-shot learning), it is even possible to learn while challenging.

i dont know, i though I think a few hundred is not enough

**Comment by QIN2DIM** [comment]
This project has been running for 9 months and the number of non-duplicate images cached locally is less than 55k.

**Comment by luanon404** [comment]
> This project has been running for 9 months and the number of non-duplicate images cached locally is less than 55k.

Ok thanks, I think I'm stupid
