### ISSUE TITLE
[Challenge] penguin surrounded by flowers

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#235]
### Prompt[en]

Please click each image containing a penguin surrounded by flowers

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=c86d730b-300a-444c-a8c5-5312e7a93628

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=c86d730b-300a-444c-a8c5-5312e7a93628

### Screenshot of the challenge

![img_v2_f4594495-d8e6-40e4-80f7-18daaa5b780g](https://user-images.githubusercontent.com/62018067/192616974-5ffcfc9b-c479-40fe-a349-c97aab3daa78.png)

**Comment by itschasa** [comment]
can you close this issue pls? since it's done

**Comment by QIN2DIM** [comment]
... 啊这
