### ISSUE TITLE
[Question] How to add ChromeOption to hcaptcha challenger?

### ISSUE THREAD

**Issue by WieszakWare** [QIN2DIM/hcaptcha-challenger#238]

**Comment by QIN2DIM** [comment]
You can add it here

https://github.com/QIN2DIM/hcaptcha-challenger/blob/8990ebea4e453a5b1229a0e450a07683805705b0/src/services/utils/toolbox/toolbox.py#L83

**Comment by QIN2DIM** [comment]
I'm maintaining a closed source version and have changed a lot of code, so I can't write documentation for now.
