### ISSUE TITLE
[Question]  Can't add extension with the python template

### ISSUE THREAD

**Issue by rabeaasdss** [QIN2DIM/hcaptcha-challenger#243]
![image](https://user-images.githubusercontent.com/111980189/193361132-00b5deb1-0328-49ef-ab17-18fbdc581732.png)
and it doesn't work

**Comment by QIN2DIM** [comment]
You should modify options before ChromeDriver starts.

But when you use new_challenger, it's already started.

**Comment by geckoy** [comment]
![image](https://user-images.githubusercontent.com/71551445/193418286-2ab14a63-7230-43f5-bc6c-c3c58240b7e0.png)
adding chrome options throw error cause already exists 
![image](https://user-images.githubusercontent.com/71551445/193418316-dc957cd4-1189-4e50-9426-6557449fed08.png)
![image](https://user-images.githubusercontent.com/71551445/193418341-f795e737-1982-4164-beb5-b8a80aa2573b.png)

**Comment by QIN2DIM** [comment]
This module was designed very * and I will redo it.

**Comment by QIN2DIM** [comment]
I made pypi to make it easier for me to use in another project, and I released pypi in almost a few hours. Therefore, I didn't design any interfaces that I couldn't use.

I will redo these interfaces.
