### ISSUE TITLE
[Question]  Capkey

### ISSUE THREAD

**Issue by Azulax90** [QIN2DIM/hcaptcha-challenger#247]
when you solve hcaptcha you get a key "P0_...." and me i want get it, you know how i can get it with ur script ?

**Comment by luanon404** [comment]
for your question: yes

**Comment by ItsCEED** [comment]
This is not made for skids, even tho is skid friendly.
But this wont help you with discord (since you already asked for it), you need a lot more stuff for discord than just solved hcap.

**Comment by Azulax90** [comment]
> This is not made for skids, even tho is skid friendly. But this wont help you with discord (since you already asked for it), you need a lot more stuff for discord than just solved hcap.

did i talk about discord?

**Comment by 2xmonth** [comment]
did you even search through the closed issues?

**Comment by luanon404** [comment]
> for your question: yes

just bypass and get it

**Comment by QIN2DIM** [comment]
you can call this API:

```python

# selenium
def get_hcaptcha_response(ctx: Chrome) -> typing.Optional[str]:
    return ctx.execute_script("return hcaptcha.getResponse()")

# playwright
def get_hcaptcha_response(page: Page) -> typing.Optionalp[str]:
    return page.evaluate("hcaptcha.getResponse()")
```

**Comment by Azulax90** [comment]
> you can call this API:
> 
> ```python
> # selenium
> def get_hcaptcha_response(ctx: Chrome) -> typing.Optional[str]:
>     return ctx.execute_script("return hcaptcha.getResponse()")
> 
> # playwright
> def get_hcaptcha_response(page: Page) -> typing.Optional[str]:
>     return page.evaluate("hcaptcha.getResponse()")
> ```
> 
> you can search more detailed on the [StackOverflow](https://stackoverflow.com/)

Tyyyy but where i put it ? ;-;

**Comment by luanon404** [comment]
> > you can call this API:
> > ```python
> > # selenium
> > def get_hcaptcha_response(ctx: Chrome) -> typing.Optional[str]:
> >     return ctx.execute_script("return hcaptcha.getResponse()")
> > 
> > # playwright
> > def get_hcaptcha_response(page: Page) -> typing.Optional[str]:
> >     return page.evaluate("hcaptcha.getResponse()")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > you can search more detailed on the [StackOverflow](https://stackoverflow.com/)
> 
> Tyyyy but where i put it ? ;-;

after bypass hcaptcha

**Comment by Azulax90** [comment]
> 

where is bypass hcaptcha
