### ISSUE TITLE
[Question] Not working in threaded environment

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#252]
I want to store it in my own location

**Comment by M-Zubair10** [comment]
I use multiprocessing function to allow max time for a function to perform, but it gives `no event loop` error in that case,
Otherwise it works perfect

**Comment by Its-Vichy** [comment]
You must provide more informations; show us your code, this seems to be mostly an error from you haha

**Comment by M-Zubair10** [comment]
Can you add timeout functionality, so in case it stuck anywhere, we'll have a backup solution
I did using timeout function of multiprocessing but it failed here due to asynchronous programming 
My function is:
```
def timeout_after(func, time_: float, args: tuple or list = (), kwargs: dict = {}):
    """
    Runs a function with time limit
    :param func: The function to run
    :param args: The functions args, given as tuple or list
    :param kwargs: The functions keywords, given as dict
    :param time_: The time limit in seconds
    :return: True if the function ended successfully. False if it was terminated.
    """
    pool = ThreadPool(processes=1)
    res = pool.apply_async(func, args=args, kwds=kwargs)
    try:
        return res.get(time_)
    except TimeoutError as e:
        return False
```
