### ISSUE TITLE
[Question] ONNX read error

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#256]
cv2.error: OpenCV(4.5.5) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:199: error: (-210:Unsupported format or combination of formats) Failed to parse ONNX model: ./datas/models/toy_turtle.onnx in function 'ONNXImporter'

This is happening to some labels only

**Comment by QIN2DIM** [comment]
reinstall toy_turtle.onnx

**Comment by D4yno** [comment]
I have the same issue with only seaplane.onnx

any help on this i would really appreciate it! 


`cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:194: error: (-5:Bad argument) Can't read ONNX file: C:\Users\source\Desktop\hcap\model\seaplane.onnx in function 'cv::dnn::dnn4_v20211220::ONNXImporter::ONNXImporter`
