### ISSUE TITLE
[Challenge] 

### ISSUE THREAD

**Issue by FuckingToasters** [QIN2DIM/hcaptcha-challenger#257]
### Prompt[en]

Please enter yes or no

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitelink

https://discord.com

### Screenshot of the challenge

Don't know, i ran the browser headerless

**Comment by QIN2DIM** [comment]
really?

**Comment by FuckingToasters** [comment]
> really?

yes, really. i don't know why this happend but it did. after restarting i got the normal image captchas again.
