### ISSUE TITLE
[Question] cv2.error: bad allocation

### ISSUE THREAD

**Issue by FuckingToasters** [QIN2DIM/hcaptcha-challenger#259]
## Brief description

I try to solve captcha on discord.com and it worked fine until now, i logged in my rdp and noticed that it start the browser, get following error, don't close the browser and just start another one. 

## Related logger
```py
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\toolcollection\DISCORDGEN\main.py", line 631, in generate_unclaimed
    captcha = await self.captcha_solver()
  File "C:\Users\Administrator\Desktop\toolcollection\DISCORDGEN\main.py", line 447, in captcha_solver
    self.challenger = ArmorCaptcha(dir_workspace=DIR_CHALLENGE, dir_model=DIR_MODEL, lang='en', debug=True,
  File "C:\Users\Administrator\Desktop\toolcollection\DISCORDGEN\hcaptcha_challenger\core.py", line 134, in __init__
    self.yolo_model = yolo.YOLO(self.dir_model, self.onnx_prefix)
  File "C:\Users\Administrator\Desktop\toolcollection\DISCORDGEN\hcaptcha_challenger\solutions\yolo.py", line 135, in __init__
    self.net = cv2.dnn.readNetFromONNX(self.onnx_model["path"])
cv2.error: bad allocation
```

**Comment by QIN2DIM** [comment]
reinstall requirements

**Comment by QIN2DIM** [comment]
Obviously, you modified the code, which may destroy its robustness. I can't see your commits, so you should solve it on google or StackOverflow.

**Comment by FuckingToasters** [comment]
> Obviously, you modified the code, which may destroy its robustness. I can't see your commits, so you should solve it on google or StackOverflow.

I didn't modifed the code in any way. It works for some time but then this issue happen and i need to restart to get it working again but i'm not sitting there, watching it 24/7 until the errorhappen again to be able to restart it.

**Comment by QIN2DIM** [comment]
> I didn't modifed the code in any way

What I mean is that you are using Challenger in your own project. Obviously you need to change part of the code of this project for you to use it properly.

**Comment by QIN2DIM** [comment]
Actually, what I want to say is this line of code

```python 
captcha = await self.captcha_solver()
```
