### ISSUE TITLE
[Question] ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.

### ISSUE THREAD

**Issue by excepts** [QIN2DIM/hcaptcha-challenger#26]
I get this error when attempting to run the program

```
ImportError: DLL load failed while importing _arpack: The specified procedure could not be found.
```

If you wish to contact me, you could either reply to this issue or contact me on discord - Socket#0001

**Comment by QIN2DIM** [comment]
```bash
pip uninstall numpy && pip install numpy==1.21.5
```

**Comment by excepts** [comment]
Thank you for the reply. I will try it when I have the chance and let you know how it goes :)

**Comment by excepts** [comment]
Hi, there is a new error

```
ImportError: DLL load failed while importing _speedup: The specified module could not be found.
```

**Comment by QIN2DIM** [comment]
what...so
What operating system are you using? Py3+? This error is too rare.

**Comment by QIN2DIM** [comment]
You just need to create a new conda env and run it. Your current environment is all messed up.
