### ISSUE TITLE
[Question] ONNXImporter 

### ISSUE THREAD

**Issue by D4yno** [QIN2DIM/hcaptcha-challenger#260]
Hello, i have installed the needed requirements with the latest pip, however im facing some weird issue regarding the cv2 and onnx import bugs on windows 10.

any help on this i would really appreciate it!

`cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:194: error: (-5:Bad argument) Can't read ONNX file: C:\Users\D4yno\Desktop\captcha_ai\model\seaplane.onnx in function 'cv::dnn::dnn4_v20211220::ONNXImporter::ONNXImporter`

**Comment by QIN2DIM** [comment]
reinstall requirements

**Comment by D4yno** [comment]
I have tried reinstalling them, no luck any other way around it?

**Comment by QIN2DIM** [comment]
```bash
# python3.10
pip install opencv-python==4.5.5.64 numpy==1.21.5
```

```bash
python main.py install --upgrade
```

**Comment by D4yno** [comment]
Unfortunately im still facing the same issue, however in my RDP it works fine it doesn't throw me any errors after requirements installed, my guess is that my pc can't handle it, or my python is bugging

  `self.challenger = ArmorCaptcha(dir_workspace=DIR_CHALLENGE, dir_model=DIR_MODEL, lang='en', debug=True,path_objects_yaml=PATH_OBJECTS_YAML, onnx_prefix="yolov5s6")
  File "C:\Users\sourc\Desktop\ZOURZ\hcaptcha_challenger\core.py", line 131, in __init__
    self.pluggable_onnx_models = self.pom_handler.overload(
  File "C:\Users\source\Desktop\ZOURZ\hcaptcha_challenger\solutions\resnet.py", line 203, in overload
    return {
  File "C:\Users\source\Desktop\ZOURZ\hcaptcha_challenger\solutions\resnet.py", line 204, in <dictcomp>
    finger: FingersOfTheGolderOrder(finger, dir_model, path_rainbow)
  File "C:\Users\source\Desktop\ZOURZ\hcaptcha_challenger\solutions\resnet.py", line 93, in __init__
    super().__init__(onnx_prefix, f"{onnx_prefix}(ResNet)_model", dir_model, path_rainbow)
  File "C:\Users\source\Desktop\ZOURZ\hcaptcha_challenger\solutions\resnet.py", line 41, in __init__
    self.net = cv2.dnn.readNetFromONNX(self.onnx_model["path"])
cv2.error: OpenCV(4.5.5) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\onnx\onnx_importer.cpp:194: error: (-5:Bad argument) Can't read ONNX file: C:\Users\source\Desktop\ZOURZ\model\seaplane.onnx in function 'cv::dnn::dnn4_v20211220::ONNXImporter::ONNXImporter'

Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x0000018EA180FD00>`

**Comment by QIN2DIM** [comment]
git pull
