### ISSUE TITLE
Puppeteer support?

### ISSUE THREAD

**Issue by galbuqp** [QIN2DIM/hcaptcha-challenger#272]
Hi, I'm JS/TS developer, is there a way to make it work with Puppeteer or any plans to port it to?

**Comment by galbuqp** [comment]
@shahzain345 I will study some content of python and try to do this, thank you!

**Comment by shahzain345** [comment]
hi @galbuqp i decided to fix it my self lol, it works now perfectly, install it and you are ready to go, https://github.com/shahzain345/puppeteer-hcaptcha-solver
if you have any problems you can create a issue at this repo

**Comment by galbuqp** [comment]
@shahzain345 ohhhh, thank you sir! I will test it :D
