### ISSUE TITLE
[Question] 3.6 gb cache weird

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#279]
I got a sudden increase in disk space and after checking my vm, I found that 3.6 gb of temp_cache, this is so weird
I know this can be removed automatically but if you should include this in pypi version, is it useful for next prediction? I don't think so

**Comment by QIN2DIM** [comment]
？

**Comment by M-Zubair10** [comment]
In datas folder there is tempcache of 3.6 gb weird

**Comment by QIN2DIM** [comment]
It is created under the "Current directory" and you can delete it manually

**Comment by M-Zubair10** [comment]
Yes but when next hit-challenge called
It should do this automatically, I am just saying to change docs a bit
