### ISSUE TITLE
[Question]Selenium

### ISSUE THREAD

**Issue by WynXC** [QIN2DIM/hcaptcha-challenger#28]
Hi 你好，想问一下如果我想把你的hcaptcha-challenger放进我的selenium的script的话，我该怎么样做？因为我试了放那个challenge.py进去但是一到hcaptcha出现的那一页好像没在solve那个hcaptcha

**Comment by QIN2DIM** [comment]
没懂。。。

**Comment by WynXC** [comment]
是这样的，我有一个selenium的script可是我是用着anti-captcha的plugin来解决hcaptcha，但是anti-captcha速度好慢也一直答错，结果回来的TOKEN的品质很差。我是想把你的这个challenger放进我的selenium的script但是我不清楚该怎么做

**Comment by QIN2DIM** [comment]
discord token generator?

**Comment by WynXC** [comment]
是的

**Comment by QIN2DIM** [comment]
现在这个项目的脚手架只提供了 demo 方法（这个项目的开源动机只是想展示一下这个解决方案的效果，没想到这个 anti-hacaptcha 有一个相当庞大的需求群体）。。。如果要移植（也即在自己的项目中调用 challenger 方法）的话有点麻烦。

我暂时未在 hcaptcha-challenger 中添加 motiondata，它无法在 discord token generator 中获取到有效的 Token，一个懂行的朋友说咱这项目被 discord 标记了。

**Comment by QIN2DIM** [comment]
你可以参考这个

**Comment by QIN2DIM** [comment]
我很忌惮自己的开源项目被人用于商业用途，但我依然会陆续推送 Pypi，但暂时并不会将 motiondata 的技术开源。

**Comment by QIN2DIM** [comment]
据某位懂行的朋友说 https://github.com/JustTalDevelops/go-hcaptcha 提供了一定程度的动态轨迹模拟函数，可以通过 Discord 的驻台脚本的检测，但挑战通过率相对略逊一筹，一般需要重试几轮。

**Comment by WynXC** [comment]
因为据我所知，cloudflare是用JavaScript来试探是机器还是人类在solve那个captcha。所以只要是用browser的automation都应该还有效的。比如说puppeteer，selenium或者是playwright，只要cloud flare的JavaScript有load到就行了。因为其他的solver比如说anti-captcha还是2captcha之类的是用requests的方式来solve那个captcha所以回来的TOKEN都没什么效果

**Comment by QIN2DIM** [comment]
这个我就不清楚了，没仔细研究过这个。按照我的经验来看，分发 Token 的必然会接收所谓 `试探脚本` 的检测结果的，所以一些比较快的解决方案会直接利用 motiondata 生成轨迹数组，然后按照接口的加解密方法存入 data 回传给上有服务（算是伪造，如果这种方法能够生效，selenium就不必响应这个动态行为）。

但总之如果你要在没有 pypi 的情况下调用的话，你可能要把整个项目代码放进去了-- 整个 challenger 有三个关键的步骤，一个是检测 checkbox 是否出现，然后 anti-checkbox 最后是识别。写个简单的逻辑按序调用即可-。-它需要传入 ctx，这个可以是 `from selenium.webdriver import Chrome` 的那个 WebDriver 对象

**Comment by WynXC** [comment]
这能和undetected-chromedriver一起用吗？如果用普通的chrome可能就会没有效果

**Comment by QIN2DIM** [comment]
我的大概构想是把 hcaptcha-challenger 做成一个本地接口服务，既可以在原页面维护 motiondata 也可以在 New Tag black page 加载 `iframe` 进行人机挑战，通过接口通信返回 Token。这样就可以提高并发率，用普通的 Chromedriver实现异步，hcaptcha-challenger 使用消息队列依次处理挑战请求。

**Comment by WynXC** [comment]
0.5秒算是很快乐，其他的solver有时候40秒过了他们多还没把TOKEN发回来。。。

**Comment by QIN2DIM** [comment]
> 0.5秒算是很快乐，其他的solver有时候40秒过了他们多还没把TOKEN发回来。。。

lmao ，这个demo你运行过了吗，我感觉已经接近极限了，再快就要手动 sleep 了笑死

**Comment by WynXC** [comment]
我试试看
