### ISSUE TITLE
[Question] Captcha RQData

### ISSUE THREAD

**Issue by ninjadoc107** [QIN2DIM/hcaptcha-challenger#280]
when I try to use the captcha answer on some sites it returns the following to me

{'captcha_key': ['captcha-required'], 'captcha_sitekey': 'b2b02ab5-7dae-4d6f-830e-7b55634c888b', 'captcha_service': 'hcaptcha', 'captcha_rqdata': '3uOsFvEYXQH97D9mqfaEGmXa8IE/Ud6w3O6LmhFnOHTUUGbjt8XLktqc2NReJ7jCxgcCCOFbhRb4YyB5Jgjgx/1B5xs38UFYUrEDjMuIVcWXLzRTqavTxXrXjNuDGIAq7qShgFKc45F5e+HPbTrZQU4AF1ZeAOLaqE5AIKPs' , 'captcha_rqtoken': 'Im81amRmRkpOWnNodXloTmN6SjVpOHNERGFjVitXb3crRXROeXdxUFBJWDZoanlBZXlNVWJTdko2NCtLMWl3Z1dXU2ZXVkE9PUZKZ2hBWDF4WGtqZjNxSG0i.Y068nA.8HePZFcx6zh_cWkS4uDsNRfwEVQ'}

normally in the captcha solver apis, it is necessary to pass the captcha_rqdata to avoid this "error", is there any way to pass the captcha_rqdata parameter in hcaptcha_challenger?

**Comment by Vinyzu** [comment]
You can pass a rq-Paramater by mocking the getcaptcha Request.
Heres my code for playwright:

https://github.com/Vinyzu/Botright/blob/main/botright/modules/hcaptcha.py#L53

Im not sure though if/how its possible to do that with selenium

**Comment by ninjadoc107** [comment]
> 

have discord?

**Comment by Vinyzu** [comment]
Its in my profile ReadMe if you mean me lol
