### ISSUE TITLE
[Question] Flagged on discord.com?

### ISSUE THREAD

**Issue by Umbrellass** [QIN2DIM/hcaptcha-challenger#292]
hello! i tried testing this challenger on discord.com but when i register, it instantly phone lock it. (its not my ip, i tested it)
(everything is ok, headers, payload, cookies)

i think its something with the hcaptcha token.

can someone help me?

**Comment by ItsCEED** [comment]
It is not, you dont know what you are doing

**Comment by ninjadoc107** [comment]
> 

from a tip
