### ISSUE TITLE
Warning None #2

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#297]
what do you mean, i am using hcaptchachallenger pypi version

_Originally posted by @M-Zubair10 in https://github.com/QIN2DIM/hcaptcha-challenger/issues/296#issuecomment-1288170096_

**Comment by QIN2DIM** [comment]
https://github.com/QIN2DIM/hcaptcha-challenger/commit/32aff479825c6db7996ac8afe27b968b4ec5561d
