### ISSUE TITLE
[Question] RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by saitishmukhametov** [QIN2DIM/hcaptcha-challenger#3]
anti-checkbox works fine, scaffold.demo and test doesnt work either, only clicks on checkbox, detects target object and done
following error occured:
![image](https://user-images.githubusercontent.com/33075246/154867408-71784036-1a28-4537-af38-e69545ff529a.png)
checked all dependencies, tried everything, but code-comments in chinese is too hard for me :( better learn it by now

**Comment by QIN2DIM** [comment]
Do you run it in 'Jupyter'? You need to delete the previous cache operation.

**Comment by QIN2DIM** [comment]
Maybe this issues will help you...

https://github.com/jupyter/notebook/issues/5663

**Comment by QIN2DIM** [comment]
> checked all dependencies, tried everything, but code-comments in chinese is too hard for me :( better learn it by now

About this...

This project was decoupled and separated from [another project](https://github.com/QIN2DIM/epic-awesome-gamer) I created, which was running on a Chinese environment. 

I will change all the necessary comments to English, but the transition will take time.

**Comment by saitishmukhametov** [comment]
Thanks a lot for the fast feedback:

```
pip install nest-asyncio
import nest_asyncio
nest_asyncio.apply()

```
this helped, seems like its a jupyter problem with async libs

https://stackoverflow.com/questions/46827007/runtimeerror-this-event-loop-is-already-running-in-python
