### ISSUE TITLE
[Challenge] skeleton ridding a bicycle

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#313]
### Prompt[en]

skeleton ridding a bicycle

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

edc4ce89-8903-4906-80b1-7440ad9a69c8

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=edc4ce89-8903-4906-80b1-7440ad9a69c8

### Screenshot of the challenge

![img_v2_12ea744f-da57-4257-b3e7-91ae7318baeg](https://user-images.githubusercontent.com/62018067/198833609-75c6619b-3ac9-4977-bf24-3d1bf871ab81.png)

**Comment by winktool** [comment]
another challenge is ```skeleton riding a bicycle```
