### ISSUE TITLE
[Question] Problem slover hcaptha 

### ISSUE THREAD

**Issue by ivakhivoff** [QIN2DIM/hcaptcha-challenger#319]
Hello, why is it too difficult to guess images that contain a background... also for some reason it only guesses "Horses" from all the elements and not everything else.
The pictures look like this.
I circled in red in the picture, you can see that there is "noise"
Does the developer plan to fix all this and will there be an update?
![1](https://user-images.githubusercontent.com/81561715/199617926-64b07e50-da1e-4ce0-8303-a73cd1d0ae1a.png)

**Comment by QIN2DIM** [comment]
I added the watermark removal method in the project, but I didn't actively enable it.

**Comment by ivakhivoff** [comment]
And when will it be active? And do you know about the problem that the captcha does not pass if there is another condition, everything is fine with horses, but for example lions - it does not work at all.

**Comment by ivakhivoff** [comment]
How can it be activated?

**Comment by QIN2DIM** [comment]
I determine whether to turn on watermark removal based on the image size. This is a legacy issue. I will train a separate enhancement model when I have time. btw what is the sitekey

**Comment by ivakhivoff** [comment]
sitekey 33f96e6a-38cd-421b-bb68-7806e1764460

For some reason, it doesn't work for me when there is a watermark and it doesn't recognize all the images, only horses, and it just misses others.

**Comment by QIN2DIM** [comment]
I added an augmentation model for horse, and I'll do lion's later in the evening when I have time.
