### ISSUE TITLE
feat(add): New challenge "Please select all the horses drawn with flowers"

### ISSUE THREAD

**Issue by adv-zl** [QIN2DIM/hcaptcha-challenger#32]
Hello, is it possible to create new solution of this new challenge? sitekey=4c672d35-0701-42b2-88c3-78380b0db560

demo: [Please select all the horses drawn with flowers](https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560)

![image](https://user-images.githubusercontent.com/16443377/164572529-29d7b8fe-7c50-4212-819e-2c5b22902807.png)
`

**Comment by QIN2DIM** [comment]
Maybe this challenge only comes up at a particular time and what I just visited saw is still the common type. I will keep an eye on this topic.

**Comment by QIN2DIM** [comment]
踏马，真是不当人了。

![image](https://user-images.githubusercontent.com/62018067/165665646-db6747c1-7814-4fa6-97fe-fd43dc8bac8a.png)
