### ISSUE TITLE
[Question] Does Motion interferes with captcha suspiciousness?

### ISSUE THREAD

**Issue by thauanvargas** [QIN2DIM/hcaptcha-challenger#326]
Basically i'm trying to figure out why a site is not validating a captcha done through hcaptcha_challenger, I wonder if motion done is related with this and how I'm able to modify this

**Comment by ItsCEED** [comment]
the lib is here to solve the captcha, not do it right.
There are many more factors than just the motion data.

**Comment by thauanvargas** [comment]
> the lib is here to solve the captcha, not do it right. There are many more factors than just the motion data.

It solves the captcha, okay, but i'm guessing the tokens generated are flagged as suspicious, so I wonder what is for the motion command and how it works

**Comment by ItsCEED** [comment]
even if you solve that, you'll get flagged again on many other things which this lib doesnt offer and i understand why.

Motion data is basically mouse movement.
