### ISSUE TITLE
[Question] platform check

### ISSUE THREAD

**Issue by 2788** [QIN2DIM/hcaptcha-challenger#33]
[这里](https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/services/hcaptcha_challenger/core.py#L255)好像判断有点问题？

ref: https://docs.python.org/3.10/library/sys.html#sys.platform
```python3
if sys.platform.startswith('win') or 'cygwin' in sys.platform:
```

**Comment by QIN2DIM** [comment]
emmm 你用的是 MacOS 运行吗。这个策略在图形化操作系统上是通用的，仅是为了区分 linux 和其他主流操作系统。

**Comment by QIN2DIM** [comment]
欸等等我在说什么

**Comment by 2788** [comment]
> emmm 你用的是 MacOS 运行吗。这个策略在图形化操作系统上是通用的，这样写仅是为了区分 linux 和其他主流操作系统。通常认为 linux 运行时是“无头的”。
> 
> 还是说你在 mac 上运行报错了。

对，我在 mac 上运行的，`asyncio.WindowsSelectorEventLoopPolicy` 不是只有 windows 上才有吗。。。我不会 python，如果我弄错了，不好意思
<img width="820" alt="image" src="https://user-images.githubusercontent.com/15196134/164713760-5e4e31b6-3b5e-4445-95ee-9da294b8978b.png">

**Comment by QIN2DIM** [comment]
我可以看一下你的报错日志嘛，你那样改动之后正常运行嘛

**Comment by 2788** [comment]
```shell
AttributeError: module 'asyncio' has no attribute 'WindowsSelectorEventLoopPolicy'
```

我改了直接正常了，效果很棒 👍
