### ISSUE TITLE
[Question] Success rate

### ISSUE THREAD

**Issue by M-Zubair10** [QIN2DIM/hcaptcha-challenger#330]
Hi,
I am assuming that cake and lemon are new types and need improvement

Lemon model is too bad, it reads oranges as mango's and sometimes banana which is not so much problem but orange is
cake -> chocolate does not have success rate

I runned 1000 tests on my captchasolver virtual machine and found that most of them failed with cake and lemon
Thankyou so much for your cool work

**Comment by APrimaveraV** [comment]
Hola Amigo, Hi from the Dominican Republic...✌🏼🇩🇴

**Comment by M-Zubair10** [comment]
Actually, example classify code doesn't work as hcaptcha_challenger do
