### ISSUE TITLE
[Question] About the model training code

### ISSUE THREAD

**Issue by Kausal-Lei** [QIN2DIM/hcaptcha-challenger#34]
This project is really useful, I want to retrain this yolov5 model to apply to my scenario, and I would be really appreciated it if you could publish your yolov5 training code.

**Comment by kilianplapp** [comment]
Training code would be very useful!

**Comment by adv-zl** [comment]
Waiting too

**Comment by shimuldn** [comment]
Me too

**Comment by 2xmonth** [comment]
if im understanding your question correctly you can just go to the yolov5 repo and follow their instructions for training

**Comment by QIN2DIM** [comment]
@2xmonth 🥂
