### ISSUE TITLE
Error in objects.yaml - feat(challenge): #341 #340

### ISSUE THREAD

**Issue by bitcoinautomatic** [QIN2DIM/hcaptcha-challenger#342]
Recent assignments are reversed:
  **chicken_on_a_tree**:
    en: [ "**chicken on the beach**" ] 
  **chicken_on_the_beach:**
    zh: [ "树上的鸡" ]
    en: [ "**chicken on a tree**" ]

Correctly:
  chicken_on_the_beach:
    zh: [ "每张海滩上包含一只鸡的图片" ]
    en: [ "chicken on the beach" ]
  chicken_on_a_tree:
    zh: [ "树上的鸡" ]
    en: [ "chicken on a tree" ]

**Comment by QIN2DIM** [comment]
😱
