### ISSUE TITLE
[Question]  Hcaptcha is using Russian Letters Now

### ISSUE THREAD

**Issue by SlotthCode** [QIN2DIM/hcaptcha-challenger#345]
My friend, TrixTM, has a bot that detects new image categories on Discord and today it started redoing new images. When we check them, it had a Russian a.
https://discord.gg/ysYpqurf
![image](https://user-images.githubusercontent.com/80789840/201967240-bee86cf2-7b2b-408d-8675-6d8a1de4ade9.png)

**Comment by TrixTM** [comment]
True ^

**Comment by TrixTM** [comment]
![2022-11-15 18 09 46](https://user-images.githubusercontent.com/20205415/201969035-65486d2a-4f86-4b23-b9c0-b0e305fbbb42.png)
I decoded the text from russian to english and this happened lol

**Comment by QIN2DIM** [comment]
![sogou20221116_012920989255](https://user-images.githubusercontent.com/62018067/201986873-506b027b-df14-44fa-aa21-9984ba2a0e57.gif)
