### ISSUE TITLE
How should i collect alot of images[Question] 

### ISSUE THREAD

**Issue by Ltooo4** [QIN2DIM/hcaptcha-challenger#350]
**Question**
How will i get 1000+ images to train my own models??

**Comment by QIN2DIM** [comment]
https://github.com/beiyuouo/hcaptcha-model-factory/issues/44

**Comment by Ltooo4** [comment]
> [beiyuouo/hcaptcha-model-factory#44](https://github.com/beiyuouo/hcaptcha-model-factory/issues/44)

tanks
