### ISSUE TITLE
[Challenge] sunflower

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#357]
### Prompt[en]

sunflower

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

91e4137f-95af-4bc9-97af-cdcedce21c8c

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=91e4137f-95af-4bc9-97af-cdcedce21c8c

### Screenshot of the challenge

![img_v2_4ceaa70c-83e6-41c6-b187-ee7a71261d0g](https://user-images.githubusercontent.com/62018067/207202375-d9761d8d-9fe0-47de-8268-33e678b7fcbf.png)

**Comment by Azulax90** [comment]
when sunflower
