### ISSUE TITLE
feat(add): Handle challenge `Please select all the elephants drawn with lеaves`

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#36]
## Usage

You can get the new feature by running the following command, btw you need to keep an eye on the update status of `rainbow.yaml`, and you can use `install` to update this module.

```bash
# hcaptcha-challenge/src
python3 main.py install
```

## Linked pull requests
@beiyuouo https://github.com/QIN2DIM/hcaptcha-challenger/pull/37

## Demo

![elephants_drawn_with_leaves-2](https://user-images.githubusercontent.com/62018067/166124484-a78208d6-9300-4b61-9336-a53d5c01b1aa.gif)

**Comment by adv-zl** [comment]
File  in _style_classification
    img = img.reshape((img.shape[0] * img.shape[1], img.shape[2])).astype(np.float64)
IndexError: tuple index out of range

**Comment by QIN2DIM** [comment]
test

**Comment by adv-zl** [comment]
numpy version 1.21.5

img = img.reshape((img.shape[0] * img.shape[1], img.shape[2])).astype(np.float64)
IndexError: tuple index out of range
[~] Finished

**Comment by adv-zl** [comment]
Can u help to solve my problem above?

**Comment by QIN2DIM** [comment]
> Can u help to solve my problem above?

Do not rush, this is a bug I deliberately left, the new challenge mode is not yet open source.

**Comment by QIN2DIM** [comment]
@adv-zl fix
