### ISSUE TITLE
[Challenge] strawberry on a plate

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#367]
### Prompt[en]

strawberry on a plate

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

![img_v2_321f12f4-0fca-4d75-be9c-240a316c8a9g](https://user-images.githubusercontent.com/62018067/207202799-62159b2d-3a8e-47c0-87fb-5ed7d5731788.png)

**Comment by cloudcaution** [comment]
Hi bro, 
Thank you so much for your work. May I know how to train the onnx model? I've search YOLOV6 repository, it is full of document explaining how good it is but no tutorial. Thanks in advance！
