### ISSUE TITLE
Hello, how to create our own onnx model?

### ISSUE THREAD

**Issue by diegoooooooooooooooo** [QIN2DIM/hcaptcha-challenger#371]
Hello, how to create our own onnx model?
because I would also like to contribute and I think it would be interesting to know the methodology to create our own model.
Please tell me where and how?
if not, give me leads so that I can conduct my research in order to be able to make my own model.

**Comment by Azulax90** [comment]
use hcaptcha factory

**Comment by diegoooooooooooooooo** [comment]
thanks i will look at this
