### ISSUE TITLE
[Challenge] residential house

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#373]
### Prompt[en]

residential house

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

91e4137f-95af-4bc9-97af-cdcedce21c8c

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=91e4137f-95af-4bc9-97af-cdcedce21c8c

### Screenshot of the challenge

![img_v2_f232a903-3161-417a-8c28-7bcb4e06ccfg](https://user-images.githubusercontent.com/62018067/208793462-07d49758-1af4-481f-b652-37c7f79a84ce.png)

**Comment by basilhe** [comment]
[residential_house.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10302089/residential_house.zip)
