### ISSUE TITLE
[Request] Documentation

### ISSUE THREAD

**Issue by TRDACommunity** [QIN2DIM/hcaptcha-challenger#375]
Hi I was wondering if any of you could make a documentation on how to use this on a actual website like discord sign up page, all I can do is using the demo one and I don't know how to use it on websites thanks.

**Comment by QIN2DIM** [comment]
We don't offer free Discord Token Generator support. Maybe you can talk to other community players.

**Comment by QIN2DIM** [comment]
We don't offer free Discord Token Generator support. Maybe you can talk to other community players.
