### ISSUE TITLE
[Challenge] Draw tight bounding box

### ISSUE THREAD

**Issue by TRDACommunity** [QIN2DIM/hcaptcha-challenger#376]
### Prompt[en]

draw a tight bounding box around the concept stated in the text below if there is more than one, choose freely

### New types of challenge

Other

### Sitekey

ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/115195849/208849571-77fc1202-fc40-4a92-8db6-adfeddba818e.png)

**Comment by QIN2DIM** [comment]
dup of #236
