### ISSUE TITLE
[Challenge] tall building

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#384]
### Prompt[en]

tall building

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

91e4137f-95af-4bc9-97af-cdcedce21c8c

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=91e4137f-95af-4bc9-97af-cdcedce21c8c

### Screenshot of the challenge

![img_v2_d9db7dbc-c598-4073-834e-2c02e25c0d5g](https://user-images.githubusercontent.com/62018067/209487089-90b3d67e-8789-4a19-acf8-1a95dc8858ca.png)

**Comment by basilhe** [comment]
resolved onnx zip file
[tall_building.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10305294/tall_building.zip)

**Comment by QIN2DIM** [comment]
想写个工作流

**Comment by QIN2DIM** [comment]
@basilhe thanks
