### ISSUE TITLE
[Challenge] desert

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#388]
### Prompt[en]

desert

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

![img_v2_e74a6351-3d2b-4b50-be6e-15491ec9899g](https://user-images.githubusercontent.com/62018067/210766178-238bb881-106e-489c-b567-4f677e6c83b1.png)

**Comment by RafaelKuhn1212** [comment]
Are you working for making this challenge?

**Comment by TranVinh-13** [comment]
> Are you working for making this challenge?

https://www.mediafire.com/file/dp1v2ufzxtu38ru/desert.onnx/file

**Comment by QIN2DIM** [comment]
> Are you working for making this challenge?

I am on vacation and may not be able to update the project for the next two weeks
