### ISSUE TITLE
Setting up for Selenium organisation?

### ISSUE THREAD

**Issue by 3cvil** [QIN2DIM/hcaptcha-challenger#397]
I have no idea what I am missing but the provided docs are useless in application - providing demonstrations of what it can do, as well as 2 pages on how to use the demo version is not helpful at all in working out how to use this program.. I am trying to automate discord accounts being made and part of the process is redirected to a page with a captcha that needs to be solved. How can I do this? I have looked at the wiki, google, project page, source code, example files, pip module - none tell me how to setup and use this project at a base level (And don't recommend me the selenium example - I've already seen it)... Where is the actual usage instructions??

**Comment by QIN2DIM** [comment]
I may need some people who are experienced with discord-GEN and willing to do open source sharing to maintain a new branch instance. I only have a basic understanding of the technology stack for AI applications and automation, not much about discord.🤷‍♀️

**Comment by 3cvil** [comment]
> I may need some people who are experienced with discord-GEN and willing to do open source sharing to maintain a new branch instance. I only have a basic understanding of the technology stack for AI applications and automation, not much about discord.🤷‍♀️

I just wanna know how to use it to solve captchas on a specific website - and not on the samples provided, ie how to use it in code, use it with webdriver to find a captcha / give html source and then hcaptcha challenger will solve it. I doubt that people will be willing to work on an open source gen though

**Comment by M-Zubair10** [comment]
@QIN2DIM Can i make selenium api for this?
Can i use this in my app?
Note: app is free

**Comment by M-Zubair10** [comment]
@everyone, releasing CaptchaXpert, hcaptcha,recaptcha,gpcaptcha,antibotlinks captcha solver in next week
Currently, support only selenium, but can be integrated with real mouse simulation

**Comment by M-Zubair10** [comment]
@M1ngXU check https://github.com/M-Zubair10/CaptchaXpert
Captcha solving is as easy as CaptchaSolver().solve(), read docs
It uses this hcaptcha challenger and my custom recaptcha solver with selenium integration

**Comment by M1ngXU** [comment]
> @M1ngXU check https://github.com/M-Zubair10/CaptchaXpert Captcha solving is as easy as CaptchaSolver().solve(), read docs It uses this hcaptcha challenger and my custom recaptcha solver with selenium integration

Thank you for the ping. But I have a question, since I am using my own modification of this repo. How do you handle fails (wrong answer or no model)?

**Comment by M-Zubair10** [comment]
Selenium clicks retry button in that case

**Comment by M-Zubair10** [comment]
And do a recursive call
However, there is no time support yet
Like you can't set timeout for it, I think we can use thread for that,
