### ISSUE TITLE
[Question] How to use `hcaptcha-challenger` in my own projects

### ISSUE THREAD

**Issue by naexxx** [QIN2DIM/hcaptcha-challenger#4]

**Comment by naexxx** [comment]
Hi, thanks for hcaptcha-challenger. Could you tell me how to add this captcha solution to your code. Thank you in advance!

**Comment by QIN2DIM** [comment]
I don't understand what you mean.😂

Do you mean how the project works?

**Comment by naexxx** [comment]
No, I want to add to my project. So that it runs with my script, waits for the captcha and solves it on my site

**Comment by QIN2DIM** [comment]
Oh, my dear friend. This project only provides a demo of a solution. The demo code is open source and you can modify it to suit your needs.

 I don't think I might be able to help. Instead, I would be interested in discussing academic issues if you would like to do so.
