### ISSUE TITLE
[Detection] Discord can detect solver

### ISSUE THREAD

**Issue by null8tr** [QIN2DIM/hcaptcha-challenger#402]
When `core.py` want to change frame by switch_to_challenge_frame discord detect it
do you have any idea

**Comment by SlotthCode** [comment]
Don't be a skid.

**Comment by SlotthCode** [comment]
TRIXS gen still works

**Comment by IamZiroToxic** [comment]
wdym

**Comment by SlotthCode** [comment]
it simple fix, discord detects undetected chromedriver

**Comment by IamZiroToxic** [comment]
It will work without captcha solver

**Comment by IamZiroToxic** [comment]
This repository when captcha shown up switch to the captcha frame that switch do a execute and that execute reason why discord detect me

**Comment by SlotthCode** [comment]
incept the request for discord.com, or do hybrid with a server side once you solve the captcha, if you want more info add me on discord. Slotth#3737 dose.lol/outerspace

**Comment by IamZiroToxic** [comment]
Ok I added you

**Comment by whhsw** [comment]
Not sure about the switch_to_challenge_frame

but this line is for sure causing detection. 

    @staticmethod
    def get_hcaptcha_response(ctx: Chrome) -> typing.Optional[str]:
        return ctx.execute_script("return hcaptcha.getResponse()")


you may refer to the discussion in these two thread.
https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1010
https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1017

**Comment by IamZiroToxic** [comment]
One reason may be this and I fixed it but switch to challenge frame execute a command but I switch to playwright
