### ISSUE TITLE
Discord can detect solver

### ISSUE THREAD

**Issue by dark987441** [QIN2DIM/hcaptcha-challenger#405]
What should I do? Help me

**Comment by Mintey1** [comment]
technically it cant detect but can in fact detect selenium so just use undetected_chromedriver instead

**Comment by eric489096** [comment]
`import undetected_chromedriver as webdriver

wd_opt = webdriver.ChromeOptions()
wd_opt.headless = True
wd_opt.add_argument("--no-sandbox")
wd_opt.add_argument("--headless")
wd_opt.add_argument("--disable-gpu")
wd_opt.add_argument("--disable-software-rasterizer") 
wd_opt.add_experimental_option("excludeSwitches", ["enable-automation"])
wd_opt.add_experimental_option('useAutomationExtension', False)
wd = webdriver.Chrome(executable_path="./data/chromedriver.exe", chrome_options=wd_opt, service_args=['--verbose'], service_log_path=None)
atexit.register(lambda *_: wd.quit())

with open(dirname(__file__) + "/js/hsw.js") as fp:
    wd.execute_script(fp.read() + "; window.hsw = hsw")
`
it didn't work, where is the problem?

**Comment by Azulax90** [comment]
undetected chromedriver = detected driver

**Comment by Mintey1** [comment]
Use subprocess it should work and worked for me

**Comment by eric489096** [comment]
@Mintey1 can you send sample code please

**Comment by eric489096** [comment]
@Azulax90 what should i use?

**Comment by Mintey1** [comment]
> @Mintey1 can you send sample code please

from selenium import webdriver
import undetected_chromedriver as uc
driver = uc.Chrome(use_subprocess=True)
###restofcode###

**Comment by dark987441** [comment]
> > @Mintey1 can you send sample code please
> 
> from selenium import webdriver import undetected_chromedriver as uc driver = uc.Chrome(use_subprocess=True) ###restofcode###

dont working

**Comment by Azulax90** [comment]
try playwright

**Comment by dark987441** [comment]
> try playwright

dont work

**Comment by M-Zubair10** [comment]
try seleniumbase, they have better uc option, if still not, try autoit or pyautogui, these can be undetected I think
