### ISSUE TITLE
[Challenge] violin

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#409]
### Prompt[en]

violin

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

![img_v2_08addf05-e338-46e2-ab2f-109bed8549dg](https://user-images.githubusercontent.com/62018067/216974654-e15547f6-78e6-402b-b16b-320545057019.png)

**Comment by ndtrongvn** [comment]
resolved onnx model
[violin.onnx.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10672120/violin.onnx.zip)

**Comment by QIN2DIM** [comment]
@ndtrongvn thanks
