### ISSUE TITLE
[Challenge] trumpet

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#411]
### Prompt[en]

trumpet

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Screenshot of the challenge

![img_v2_b9d595f8-f706-4fb7-9350-b410dd51b03g](https://user-images.githubusercontent.com/62018067/217404194-31769009-047a-4ba6-99c3-f5cccaa89ee6.png)

**Comment by ndtrongvn** [comment]
resolved model
[trumpet.onnx.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10686749/trumpet.onnx.zip)

**Comment by QIN2DIM** [comment]
[trumpet.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10687266/trumpet.zip)

**Comment by QIN2DIM** [comment]
@ndtrongvn thanks
