### ISSUE TITLE
[Challenge] beach

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#412]
### Prompt[en]

beach

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

edc4ce89-8903-4906-80b1-7440ad9a69c8

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=edc4ce89-8903-4906-80b1-7440ad9a69c8

### Screenshot of the challenge

![img_v2_6cb5e014-b016-4981-988c-0c15130bca9g](https://user-images.githubusercontent.com/62018067/217404257-adba4fa6-0988-447c-8b9f-be65ebd51e25.png)

**Comment by ndtrongvn** [comment]
resolved model
[beach.onnx.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10686742/beach.onnx.zip)

**Comment by QIN2DIM** [comment]
[beach.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10687270/beach.zip)

**Comment by QIN2DIM** [comment]
@ndtrongvn thanks
