### ISSUE TITLE
[Challenge] pineapple on pizza

### ISSUE THREAD

**Issue by ndtrongvn** [QIN2DIM/hcaptcha-challenger#414]
### Prompt[en]

pineapple on pizza

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/37130428/217583096-e3e947c0-65c4-4017-878c-d862242a40a5.png)

**Comment by QIN2DIM** [comment]
emmm, I want to give you permission to upload the model and submit pr.

**Comment by QIN2DIM** [comment]
I have been busy lately, and I will write a set of CI workflows to do this automatically in a while. Thank you for your support of this project!✨

**Comment by ndtrongvn** [comment]
Okay, I'll upload the model and update the main branch's ```objects.yaml``` directly
