### ISSUE TITLE
[Challenge]  Fried egg on a bread

### ISSUE THREAD

**Issue by Sysys242** [QIN2DIM/hcaptcha-challenger#417]
### Prompt[en]

Please click on each image containing a fried egg on a bread

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/86845555/218057885-c48c51c1-81b3-4bc6-84f0-50f89d481dc4.png)

**Comment by bitcoinautomatic** [comment]
[fried_egg_on_a_bread.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10706187/fried_egg_on_a_bread.zip)

**Comment by bitcoinautomatic** [comment]
> ### Prompt[en]
> Please click on each image containing a fried egg on a bread
> 
> ### New types of challenge
> New prompt (for ex. Please select all the 45th President of the US)
> 
> ### Sitekey
> 4c672d35-0701-42b2-88c3-78380b0db560
> 
> ### Sitelink
> https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560
> 
> ### Screenshot of the challenge
> ![image](https://user-images.githubusercontent.com/86845555/218057885-c48c51c1-81b3-4bc6-84f0-50f89d481dc4.png)

[fried_egg_on_a_bread.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10706230/fried_egg_on_a_bread.zip)

**Comment by QIN2DIM** [comment]
emmm, How many datasets do you usually train with

**Comment by QIN2DIM** [comment]
@Sysys242 @bitcoinautomatic thanks!

**Comment by bitcoinautomatic** [comment]
> emmm, How many datasets do you usually train with

5000-10000k

**Comment by QIN2DIM** [comment]
> > emmm, How many datasets do you usually train with
> 
> 5000-10000k

awesome!
