### ISSUE TITLE
hcaptcha images

### ISSUE THREAD

**Issue by mewzax** [QIN2DIM/hcaptcha-challenger#421]
hello, can you upload the images you used to train the models too pls ?

**Comment by Azulax90** [comment]
bahhahaha sale skid

**Comment by mewzax** [comment]
> bahhahaha sale skid

g juste la flemme de scrape les img moi au moins je sais comment print des caractères dans une console

**Comment by mewzax** [comment]
gg tu sais use colorama

**Comment by Azulax90** [comment]
oe vrmt 100% colorama

**Comment by sfx2me** [comment]
> bahhahaha sale skid

Should I remind you of the issues you opened?💀

**Comment by QIN2DIM** [comment]
- https://github.com/captcha-challenger/hcaptcha-whistleblower

**Comment by mewzax** [comment]
thx u r so cool
