### ISSUE TITLE
[Challenge] bear in the water

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#424]
### Prompt[en]

bear in the water

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

![img_v2_73b76302-3fcb-4341-a47f-8dde32f8ea7g](https://user-images.githubusercontent.com/62018067/219655358-710bff9c-b4c3-4c8b-9357-688773d68692.png)

**Comment by Azulax90** [comment]
https://cdn.discordapp.com/attachments/1060016961557373028/1076525191867408464/bear_in_the_water.onnx
