### ISSUE TITLE
[Challenge] hand watches

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#426]
### Prompt[en]

hand watches

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

c86d730b-300a-444c-a8c5-5312e7a93628

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=c86d730b-300a-444c-a8c5-5312e7a93628

### Screenshot of the challenge

![img_v2_3fd3f218-cf78-496e-9ba8-7d1b114c2c9g](https://user-images.githubusercontent.com/62018067/219655519-2b4ca0d9-aedc-45bc-bef7-d11675e9ba02.png)

**Comment by Elbouchouki** [comment]
![image](https://user-images.githubusercontent.com/36736786/219720702-2f022b73-8198-4e86-b4e1-bd911a05d81f.png)

**Comment by Sysys242** [comment]
By azulex

https://cdn.discordapp.com/attachments/997150957542588499/1076507184298459187/hand_watches.onnx

**Comment by Azulax90** [comment]
![image](https://user-images.githubusercontent.com/113309764/219870862-15ebb7b2-dd40-40c1-b831-1cf8c29a1b36.png)

**Comment by ndtrongvn** [comment]
Thanks @Azulax90
