### ISSUE TITLE
[Challenge] hockey match

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#429]
### Prompt[en]

hockey match

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

c86d730b-300a-444c-a8c5-5312e7a93628

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=c86d730b-300a-444c-a8c5-5312e7a93628

### Screenshot of the challenge

![img_v2_1508a561-0535-48ac-9142-8b1b768dd42g](https://user-images.githubusercontent.com/62018067/219718789-96f08b4a-dea5-4497-8426-650fc75c12d3.png)

**Comment by Sysys242** [comment]
By Azulex

https://cdn.discordapp.com/attachments/997150957542588499/1076507202103283722/hockey_match.onnx

**Comment by Azulax90** [comment]
![image](https://user-images.githubusercontent.com/113309764/219870846-4dcb321e-43e4-47a9-94a5-874878871fda.png)
