### ISSUE TITLE
[Question] does discord flag it?

### ISSUE THREAD

**Issue by itschasa** [QIN2DIM/hcaptcha-challenger#43]
is discord flagging this program? cheers

**Comment by Its-Vichy** [comment]
i have made gen with it ;), you just need to make somes changes

**Comment by itschasa** [comment]
> i have made gen with it ;), you just need to make somes changes

changes to the solving part? or just getting the token part?

**Comment by Mewzax** [comment]
> i have made gen with it ;), you just need to make somes changes

ahah je savais bien que t'avais utilisé une src
