### ISSUE TITLE
[Challenge] Soccer Ball

### ISSUE THREAD

**Issue by M1ngXU** [QIN2DIM/hcaptcha-challenger#435]
### Prompt[en]

Please click each image containing a soccer bаll

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=6ba78ccd-f275-4c2d-be45-5e4b46a4a4d8

### Screenshot of the challenge

![1677007891 soccer ball](https://user-images.githubusercontent.com/91617361/220441500-e08b6a0a-3522-441f-91f6-c20cbf2e82bf.png)

**Comment by ndtrongvn** [comment]
duplicated #434
