### ISSUE TITLE
[Challenge] cow in its natural

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#436]
### Prompt[en]

cow in its natural

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Screenshot of the challenge

![img_v2_dc6ef70d-b319-4ef8-8c6d-1d564bc09eag](https://user-images.githubusercontent.com/62018067/220811736-8affa1c6-4871-41a8-8143-f8f5240f85a0.png)

**Comment by yeyuchen198** [comment]
![image_2023-02-28_12-59-13](https://user-images.githubusercontent.com/89305403/222030532-89338173-629c-42cc-b839-e02024b33a34.png)

cow_in_its_natural_environment:
    zh: [ "母牛在其自然环境中", "自然环境中的奶牛" ]

**Comment by ndtrongvn** [comment]
@yeyuchen198 added. Thanks
