### ISSUE TITLE
[Challenge] someone playing football

### ISSUE THREAD

**Issue by Mouad-scriptz** [QIN2DIM/hcaptcha-challenger#437]
### Prompt[en]

Please click each image containing someone playing football

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

discord.com

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/102869034/221362632-452708c5-2a24-4f75-95b5-7f7196a44e13.png)

**Comment by discordsellertop** [comment]
[someone_playing_football.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/10833256/someone_playing_football.zip)
Dataset  - Yes: 3218 img, Bad: 5502 img.
I seller discord, write to telegram @badredhat
👍
