### ISSUE TITLE
[Challenge] robot

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#438]
### Prompt[en]

robot

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

c86d730b-300a-444c-a8c5-5312e7a93628

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=c86d730b-300a-444c-a8c5-5312e7a93628

### Screenshot of the challenge

![img_v2_b9703f5b-34c9-46e2-9294-6bd9007020dg](https://user-images.githubusercontent.com/62018067/221503079-888c90d8-e98b-4b49-b3bf-62f85e4d8367.png)

**Comment by QIN2DIM** [comment]
wtf??

**Comment by Azulax90** [comment]
yes
