### ISSUE TITLE
feat(add): Happy Hunger Games! | airplane_with_watermark

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#44]
## Linked pull requests

@beiyuouo https://github.com/QIN2DIM/hcaptcha-challenger/pull/45

## Demo
-> [target sitekey](https://accounts.hcaptcha.com/demo?sitekey=91e4137f-95af-4bc9-97af-cdcedce21c8c)

<p><img width="45%" src="https://user-images.githubusercontent.com/62018067/171321170-cc5224d5-71cd-4639-a7ee-e7992add8371.gif"></img></p>

**Comment by QIN2DIM** [comment]
boring challenge

**Comment by syzen77777777777** [comment]
is the challenge already solving this captcha?

**Comment by QIN2DIM** [comment]
> is challenger solve it?

It's a simple trick.

In the next few days I have to deal with academic matters. I'll sync the solution to the GitHub repository when I have some time. Thanks for your interest in our work.

**Comment by syzen77777777777** [comment]
is the challenge already resolved?

**Comment by QIN2DIM** [comment]
fixed
