### ISSUE TITLE
[Question] does not change captcha if you find one that still has no support to solve

### ISSUE THREAD

**Issue by Laranjo1** [QIN2DIM/hcaptcha-challenger#440]
## Brief description

Good morning, I'm trying to solve the problem of not being able to change Captcha whenever I find one that still does not exist a onnx to solve it

## Related logger
 gets stuck infinitely here:
````WARNING - >> ALERT [ArmorCaptcha] Types of challenges not yet scheduled - label=「hallway」 prompt=「Please click each image containing a һаllway」 screenshot= site_link=https://www.habbo.com/api/public/captcha issues=https://github.com/QIN2DIM/hcaptcha-challenger/issues?q=hallway````
I already checked the Refresh-Button class and it's correct, I'm calling it in the code but it still does not change the captcha
I also tried to use the skip button and didn't get results((By.XPATH, '//div[@class="button-submit button" and @title="Skip Challenge"]'))

```markdown
code: 
def hit_challenge(ctx, challenger: HolyChallenger, retries: int = 10) -> typing.Optional[str]:
    # Tentar resolver o desafio hCaptcha
    if challenger.utils.face_the_checkbox(ctx):
        challenger.anti_checkbox(ctx)
        if res := challenger.utils.get_hcaptcha_response(ctx):
            return res

    for _ in range(retries):
        try:
            if (resp := challenger.anti_hcaptcha(ctx)) is None:
                continue
            if resp == challenger.CHALLENGE_SUCCESS:
                return challenger.utils.get_hcaptcha_response(ctx)
        except ChallengePassed:
            return challenger.utils.get_hcaptcha_response(ctx)
        challenger.utils.refresh(ctx)
        time.sleep(1)
```

**Comment by M1ngXU** [comment]
can you try to manually click the refresh button? this worked for me. also, make sure to be in the correct context

**Comment by yeyuchen198** [comment]
如果出现未支持的Model，可以刷新或者跳过，直到出现受支持的Modal

**Comment by DonJ0n** [comment]
im having the same issue and cant get it to learn how to  solver the chair one, any luck on your end?
