### ISSUE TITLE
[Challenge] 

### ISSUE THREAD

**Issue by Darknessycdw** [QIN2DIM/hcaptcha-challenger#443]
### Prompt[en]

Please click each image containing a cat

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=

### Sitelink

https://maximedrn.github.io/hcaptcha-solver-python-selenium/

### Screenshot of the challenge

https://i.imgur.com/IQNi10E.jpg

**Comment by ndtrongvn** [comment]
Please create valid format (title, screenshot, etc.) of challenge.
