### ISSUE TITLE
feat(pending): hcaptcha-whistleblower release

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#447]
**hCaptcha Whistleblower** is a simple project that listens for new challenges in hCaptcha and has been running steadily for a year. I will make it open source in the near future.

![image](https://user-images.githubusercontent.com/62018067/223685616-375c90fd-2014-4d58-8800-82109c927ad7.png)

![image](https://user-images.githubusercontent.com/62018067/223686072-848813ac-1dd6-48d4-b348-c8a217798189.png)

**Comment by kilianplapp** [comment]
Looking forward to it!

**Comment by QIN2DIM** [comment]
ALL YOUR NEED

- https://github.com/captcha-challenger/hcaptcha-whistleblower
