### ISSUE TITLE
[Challenge] bird sitting in a tree

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#449]
### Prompt[en]

bird sitting in a tree

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

![img_v2_fb7e9f6c-0745-4032-8a5a-c03514c577dg](https://user-images.githubusercontent.com/62018067/223686484-76e37dc0-c56c-4951-b951-815ef086f924.png)

**Comment by Arisunecik** [comment]
+
