### ISSUE TITLE
[Challenge] dog wearing sunglasses

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#453]
### Prompt[en]

dog wearing sunglasses

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

![img_v2_d24eaf31-7152-4567-9832-80f659b908dg](https://user-images.githubusercontent.com/62018067/223687126-415b9e3b-a06d-44e8-993a-f430a82f3e5e.png)

**Comment by berlin0005** [comment]
damn
