### ISSUE TITLE
[Challenge] basketball

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#455]
### Prompt[en]

basketball

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Screenshot of the challenge

![img_v2_14e9b255-a533-4327-92aa-fa3957f57b9g](https://user-images.githubusercontent.com/62018067/223820063-9e79d9c1-00aa-48b6-aa47-39317610b4dd.png)

**Comment by berlin0005** [comment]
can u fix soon sir ..?!
