### ISSUE TITLE
[Blog] Bot Revolution 

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#457]
## You know Who I Am 🤖

![image](https://user-images.githubusercontent.com/62018067/225232056-b31da9d8-02a8-4bf0-adf6-fba10ed8bbb8.png)

## Related Blogs

- #218 
- #159 

## Related Challenges

- #82 
- #176 
- #236 
- #241 
- #459 
- #471 
- #479

**Comment by ndtrongvn** [comment]
As a human, I don't even know if the dog is (really) smiling or what the kitten's age is 😅

**Comment by M1ngXU** [comment]
> As a human, I don't even know if the dog is (really) smiling or what the kitten's age is 😅

maybe that’s how you tell bots and humans apart

**Comment by QIN2DIM** [comment]
> > As a human, I don't even know if the dog is (really) smiling or what the kitten's age is 😅
> 
> maybe that’s how you tell bots and humans apart

I'M THE MACHINE. 🤖

**Comment by M1ngXU** [comment]
> > > As a human, I don't even know if the dog is (really) smiling or what the kitten's age is 😅
> > 
> > 
> > maybe that’s how you tell bots and humans apart
> 
> I'M THE MACHINE. 🤖

so you are writing code to prove that you are a human?
