### ISSUE TITLE
[Question]  Challenger is crashing when hcaptcha solves instantly

### ISSUE THREAD

**Issue by nicros22** [QIN2DIM/hcaptcha-challenger#46]
I found where exception occurs (\services\hcaptcha_challenger\core.py)
![изображение](https://user-images.githubusercontent.com/53085664/171366520-2b73b136-5be2-4745-afdb-25ce76fa0c1c.png)
I tried to call the challenge_success function or just return CHALLENGE_SUCCESS but it didn't work for me. What do I need to do? maybe change the exception itself ChallengePassed?

**Comment by nicros22** [comment]
When I click on the captcha, it is solved instantly without showing pictures. Because of this, it shows this exception and exits. What do I need to do to make the script work further and ignore this exception?
![изображение](https://user-images.githubusercontent.com/53085664/171405569-288273e9-f17c-42b7-acd9-4af681ba192d.png)

**Comment by QIN2DIM** [comment]
emmmm?

```python
try:
  get_label(ctx)
except ChallengePassed:
  pass

```

**Comment by QIN2DIM** [comment]
really? @xxhtx1337 🤦‍♂️Please go and discuss with your TokenMan how to solve your problem.

**Comment by QIN2DIM** [comment]
You're right, I misjudged it, I'll fix that later.
