### ISSUE TITLE
[Question] when would the solver be requests

### ISSUE THREAD

**Issue by skaaddd** [QIN2DIM/hcaptcha-challenger#462]
i got the data for requests and also a base of it
it could be used as text solving or image solving
i think that selenium is flagged of hcaptcha as motionData has appear this , 
"onLine": "true", "webdriver": "true", "bluetooth": {}, "clipboard": {}, "credentials": {}, "keyboard": {}, "managed": {}, "mediaDevices": {}, "storage": {}, "serviceWorker": {}, "virtualKeyboard": {}, "wakeLock": {}, "deviceMemory": 8, "ink": {}, "hid": {}, "locks": {}, "mediaCapabilities": {}, "mediaSession": 

I dont think using playright does the thing as well, as i suggest maybe use pyputeer as it has high quality with fingerprint also using chromnium browser instead of driver.

if u need or wants to contact for requests based solver to create together here is my info louissiu1998#9601

**Comment by Azulax90** [comment]
LOL

**Comment by bigboy-baby** [comment]
Dude u gotta make ur own solver not use the prebuilt one
