### ISSUE TITLE
[Question] What does it mean to load different model objects from object.yaml? Isn't there only one model trained?

### ISSUE THREAD

**Issue by kuokay** [QIN2DIM/hcaptcha-challenger#463]
What does it mean to load different model objects from object.yaml? Isn't there only one model trained?
![微信图片_20230316214345](https://user-images.githubusercontent.com/60090512/225640995-2c573279-7500-4d7c-9331-291ad0adadfd.jpg)

**Comment by QIN2DIM** [comment]
The models in [releases](https://github.com/QIN2DIM/hcaptcha-challenger/releases/tag/model) will be downloaded on demand.
