### ISSUE TITLE
[Question] Running head-fully on Linux

### ISSUE THREAD

**Issue by randrej** [QIN2DIM/hcaptcha-challenger#466]
## Brief description

Is there a way to run head-fully on Linux, and if not, why not?

I see that the `silence` parameter gets hardcoded to `True` on Linux: https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/hcaptcha_challenger/_scaffold/__init__.py#L138

Why is this so?

**Comment by QIN2DIM** [comment]
Of course, head-fully drivers (Playwright/Selenium) can be run on Linux, but the specific situation is more complicated.

1. If the operating system has a GUI interface, then the driver can be directly run.

2. If the operating system only has a command-line interface, explicitly starting the browser will result in an error. We need to use some other tools to run a visible browser interface.

**Comment by randrej** [comment]
I do my crawling on Linux, in Docker. This combo doensn't have a GUI in the usual case. However, I run (in the background) a combination X-server-plus-vnc-server (Xtigervnc) and a lightweight DM (openbox) before running the crawler, I export `DISPLAY=:0`, and this allows me to have a GUI for Chrome to use.

Having VNC access into the crawler is a game-changer for finding new edge cases. I can have the crawler leave the non-conforming page open and shoot me an e-mail. I can then VNC into the crawler container and inspect the page to see what's wrong and maybe immediately add new rules for crawling.

I tried manually changing that code to allow headful crawling on Linux (`sed -i -e 's/or "linux" in sys.platform //g' .../python3.10/site-packages/hcaptcha_challenger/_scaffold/__init__.py`), and it works perfectly fine. Maybe we could add some different way of checking if there's a GUI on Linux, like `silence = True if silence is None or ("linux" in sys.platform and "DISPLAY" not in os.environ) else silence`; `DISPLAY` is only required for X11, so I don't know how to handle Wayland, but it's a step up.

**Comment by QIN2DIM** [comment]
> Maybe we could add some different way of checking if there's a GUI on Linux

yeah, you're right.

> Having VNC access into the crawler is a game-changer for finding new edge cases. I can have the crawler leave the non-conforming page open and shoot me an e-mail.

> DISPLAY is only required for X11, so I don't know how to handle Wayland, but it's a step up. I fail to see a reason why you'd need Wayland for crawling vs X11.

I was really thoughtless about this. It was a little out of my depth. When I test the project in the virtual machine(Ubuntu Desktop), I always manually comment out this line of code to ensure that the head-fully browser runs directly.

Then there is the issue of "edge cases", where it seems possible to save screenshots and page source code（`.mhtml`） using a headless browser (similar to what human eyes see) .

**Comment by randrej** [comment]
> Then there is the issue of "edge cases", where it seems possible to save screenshots and page source code（.mhtml） using a headless browser (similar to what human eyes see) .

I used to do that, but most of the time, I have to do 2 or 3 things when I encounter an 'edge case' such as a new nag modal. Most of the time I don't get these immediately, only after `n` requests or seconds. So, if I just save a page and screenshot, I can program in one step (not multiple because the token or something has timed out), and then I have to wait once or twice more to catch the next couple of steps, to see which element's loading I need to wait for, etc.

I think my proposed solution (`silence = True if silence is None or ("linux" in sys.platform and "DISPLAY" not in os.environ) else silence`) solves this issue well enough. Shall I make a PR?

**Comment by QIN2DIM** [comment]
✅YEAH
