### ISSUE TITLE
TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by Sysys242** [QIN2DIM/hcaptcha-challenger#47]
Hey, 
So i want to use this in my project, but, it's instantly close, it can be on my project or the demo
![image](https://user-images.githubusercontent.com/86845555/171556440-4f4ad8b6-7a60-432f-8dab-f35fbdad726b.png)
I got that;

I have python 3.7.8 and google chrome, i don't know why it crash, any idea?

**Comment by QIN2DIM** [comment]
restart
