### ISSUE TITLE
[*Challenge] Select the most accurate description of the image.

### ISSUE THREAD

**Issue by ndtrongvn** [QIN2DIM/hcaptcha-challenger#472]
### Prompt[en]

Select the most accurate description of the image.

### New types of challenge

New approach (for ex. image watermark)

### Sitekey

4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/37130428/227666515-85791748-9745-40ca-afb6-4ebb769c6594.png)

**Comment by ndtrongvn** [comment]
This challenge has come up often lately. 😰

**Comment by QIN2DIM** [comment]
Trust me, human challenge is a dying industry.  I'll try to push a new model that solves this multi-modal challenge at a stroke. It'll take a while. I'm busy with other things right now. :(

🤖 But I hope hCaptcha recognizes that an industry crisis is coming. 

follow that: 
- #457

**Comment by Azulax90** [comment]
this challenge is ez

**Comment by M-Zubair10** [comment]
I think clip performed on two images for similarity will do this job
