### ISSUE TITLE
[*Challenge]  please click the center of the X

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#479]
### Prompt[en]

please click the center of the X

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

<img width="33%" src="https://user-images.githubusercontent.com/62018067/228717480-ce5d1aad-6caa-44d6-84f5-741be558ccc6.png"><img width="33%" src="https://user-images.githubusercontent.com/62018067/228717501-fd929131-08b4-44c1-9a46-ab04b15653c2.png"><img width="33%" src="https://user-images.githubusercontent.com/62018067/228717547-2a6ca6a4-b219-44ba-af88-cf0c114dc2ea.png">

<img width="33%" src="https://user-images.githubusercontent.com/62018067/228727710-9561c04a-2cbb-434f-8b76-511fd0201e01.png"><img width="33%" src="https://user-images.githubusercontent.com/62018067/228727731-5943eac0-41f1-42a2-af9f-f8a350b93ad4.png">

**Comment by Littlesnaegg** [comment]
Hey, do you have any estimation on when this will be implemented in hcaptcha-challenger ?

**Comment by jhx-zc** [comment]
> Hey, do you have any estimation on when this will be implemented in hcaptcha-challenger ?

as soon as possible.plz

**Comment by M-Zubair10** [comment]
This challenge can be solved using zero shot object detector such as grounding dino

Get box coordinates using model, then get its center point and click on it

@QIN2DIM what do you think?

**Comment by QIN2DIM** [comment]
I had a vague idea a long time ago, but I never got around to it. In general, I wanted to package the model as ONNX to run on the client side, and keep it as small as possible.

<div align="center"><img width="40%" src="https://user-images.githubusercontent.com/62018067/233539762-a675c07a-e2cd-4543-8fd5-ba7c00b4612b.png"><img width="40%" src="https://user-images.githubusercontent.com/62018067/233539755-1c64e3f3-0521-4361-ade7-a35173845c5a.png"></div>

**Comment by Vinyzu** [comment]
Maight be interesting:
https://github.com/facebookresearch/segment-anything
https://github.com/Anything-of-anything/Anything-3D

**Comment by QIN2DIM** [comment]
dup of #588
