### ISSUE TITLE
[Question] It works fast... But fail on 4/5 captchas...

### ISSUE THREAD

**Issue by Orafilynie** [QIN2DIM/hcaptcha-challenger#487]
Hello,

Is it normal that it fails excessively, i know its normal but 4/5 is a little excessive so it is due to my pc not computing the model not correctly ?

Note even for me its very hard for the t-shirt challenge due to their weird generated AI image...

Best regards, Thanks.

**Comment by ndtrongvn** [comment]
We'll retrain the t-shirt model soon, because the Hcaptcha has updated with some miscellaneous objects for this challenge.

**Comment by Orafilynie** [comment]
Thanks for your answer :)

**Comment by fretax** [comment]
hello, how do we get the model home?

**Comment by ndtrongvn** [comment]
> hello, how do we get the model home?

Did you mean "how to build the model?" ?

**Comment by fretax** [comment]
yes how to build the model by adding other challenges so that when there are updates I can update the model because I noticed that the official repository that I cloned its success rate is 2/8, I do not know why

**Comment by ndtrongvn** [comment]
DIY here: [beiyuouo/hcaptcha-model-factory](https://github.com/beiyuouo/hcaptcha-model-factory)
You must verify classified images because the auto-classification feature of `hcaptcha-model-factory` only classifies explicit objects. See more at #428

**Comment by ndtrongvn** [comment]
> We'll retrain the t-shirt model soon, because the Hcaptcha has updated with some miscellaneous objects for this challenge.

updated
