### ISSUE TITLE
[Challenge] Please click each image containing a camera

### ISSUE THREAD

**Issue by TrixTM** [QIN2DIM/hcaptcha-challenger#489]
### Prompt[en]

Please click each image containing a camera

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/20205415/230761071-f718c012-9fe2-4891-b531-a2b2b49626e2.png)

**Comment by Hydroxzz** [comment]
trixtm gen $$$ not all locked and skidded $$$$

**Comment by jankiki87** [comment]
![Przechwytywanie](https://user-images.githubusercontent.com/112200369/230900951-3e79762c-c34d-449c-ab7c-0cf071c76d04.PNG)
NEEED KEETLE

**Comment by Euro-pol** [comment]
TRIXTM GEN ON TOP ?!

**Comment by purpl3r0se** [comment]
skidded
