### ISSUE TITLE
[Challenge] refrigerator

### ISSUE THREAD

**Issue by Vinyzu** [QIN2DIM/hcaptcha-challenger#495]
### Prompt[en]

Please click each image containing a refrigerator

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitelink

epicgames.com

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/50874994/231496810-99b99022-bc20-4e6b-b6fd-a1e86d53327b.png)

**Comment by okyanusoz** [comment]
I also see it like this:

<img width="413" src="https://user-images.githubusercontent.com/46757266/233080888-e6483cbb-c2d3-4afd-880b-786013143a80.png">

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560
