### ISSUE TITLE
[Challenge] Please click each image containing a refrigerator

### ISSUE THREAD

**Issue by Shearkeyy** [QIN2DIM/hcaptcha-challenger#499]
### Prompt[en]

Please click each image containing a refrigerator

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://discord.com

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/106593315/231583120-217ca7c9-22df-4615-a34d-5cfa9e8a9957.png)

**Comment by ndtrongvn** [comment]
#495
