### ISSUE TITLE
feat(pending): mouse motionData - Improvement | demo

### ISSUE THREAD

**Issue by Its-Vichy** [QIN2DIM/hcaptcha-challenger#50]
Spoof the mouse motion data, or move the mouse to the corect tile before clicking, this will make less fraud score

**Comment by QIN2DIM** [comment]
I had a closed source version of this feature available six months ago, but obviously hCAPTCHA doesn't have the ability to calculate motion data threat scores at this point, so I'm not considering architectural tweaks for "a particular application scenario."

**Comment by Its-Vichy** [comment]
Just check my edit,
https://github.com/Its-Vichy/working-token-gen/blob/main/apis/scaffold/challenge.py

bad motionData will create bad score.

Btw good job

**Comment by QIN2DIM** [comment]
u need to make the mouse track as close to the Bezier curve as possible, and second, try to make the track point revolve around a small area.

**Comment by Its-Vichy** [comment]
Okey ;p

**Comment by QIN2DIM** [comment]
dup of #40

**Comment by QIN2DIM** [comment]
Do you know how to define "good"? I wanted to try to make a demo component, but I didn't know how to quantify the threat score, or intuitively evaluate "does it look like a person" and "so much so that the human eye can't tell".

**Comment by Its-Vichy** [comment]
This is legit mouse curve,
![image](https://user-images.githubusercontent.com/66045929/172215556-efbbcbde-4a13-4f43-a485-d582efe395a5.png)

Also check the github repo of "pyclick" library

**Comment by QIN2DIM** [comment]
awesome work ~ @Snowad14 
- https://www.binarydefense.com/mimicking-human-activity-using-selenium-and-python/
- https://github.com/stacycreasey/Browsing-Bot
