### ISSUE TITLE
[Challenge] Please click each image containing a telescope

### ISSUE THREAD

**Issue by Shearkeyy** [QIN2DIM/hcaptcha-challenger#503]
### Prompt[en]

Please click each image containing a telescope

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://discord.com

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/106593315/232179749-1b5a9149-f666-4daf-8770-9d9dba53f3f7.png)

**Comment by Summaw** [comment]
I am still getting the same thing, also same for the camera image.
