### ISSUE TITLE
ROAST CHICKEN FREEWAY 

### ISSUE THREAD

**Issue by jankiki87** [QIN2DIM/hcaptcha-challenger#504]
### Prompt[en]

ROAST CHICKEN FREEWAY

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=

### Sitelink

btcadspace

### Screenshot of the challenge

![Przechwytywanie](https://user-images.githubusercontent.com/112200369/232291667-3fb996ed-deaa-4d35-a00a-26f2d7eaa4d1.PNG)
![2](https://user-images.githubusercontent.com/112200369/232291671-dabb96f5-bfc7-4d9e-86c1-f78bb8e5363c.PNG)

**Comment by ndtrongvn** [comment]
#510
#509
