### ISSUE TITLE
[Challenge] containing a roast chicken

### ISSUE THREAD

**Issue by berlin0005** [QIN2DIM/hcaptcha-challenger#510]
### Prompt[en]

Please click each image containing a roast chicken

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://discord.com

### Screenshot of the challenge

![photo_2023-04-16_03-24-49](https://user-images.githubusercontent.com/126329125/232410922-3a593e75-a0e5-4466-af5e-91e04ed8a8b2.jpg)

**Comment by nevox12** [comment]
same thing
