### ISSUE TITLE
[Question] Is it possible to integrate into own project

### ISSUE THREAD

**Issue by Tescoo** [QIN2DIM/hcaptcha-challenger#52]
I am unable to find a way to integrate this into my own project using the module.
Is there any more detailed documentation?
Or could you help me out?

**Comment by dinuka-dev** [comment]
Same here, don't know how to add this to existing selenium project

**Comment by shahzain345** [comment]
Well please take a look at the source, and make your own version of it.

Heres how you could get the captcha_respone or the "captcha_key",

```py
hcaptcha_response = ctx.execute_script("return hcaptcha.getResponse();")
```
