### ISSUE TITLE
[Challenge] 

### ISSUE THREAD

**Issue by PABLO4316** [QIN2DIM/hcaptcha-challenger#528]
### Prompt[en]

Please click each image containing a lighthouse

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Sitelink

discord.com

### Screenshot of the challenge

![1682527779 lighthouse](https://user-images.githubusercontent.com/117773032/234660685-dde018ae-60b2-4111-982e-2d702e8b0648.png)
![1682527794 lighthouse](https://user-images.githubusercontent.com/117773032/234660722-86f97c48-ba94-497e-9fef-dcb373c2a7e1.png)
![1682527806 lighthouse](https://user-images.githubusercontent.com/117773032/234660745-9a488ef5-58ae-41f1-aa67-68e856e20e33.png)
![1682527888 lighthouse](https://user-images.githubusercontent.com/117773032/234660752-d8818ebb-ed9b-4841-911f-b44595737484.png)
![1682531279 lighthouse](https://user-images.githubusercontent.com/117773032/234660772-8d2fb2a9-9414-453b-9432-8588ed4c97a3.png)

![1682527801 lighthouse](https://user-images.githubusercontent.com/117773032/234660747-4814a376-6ca1-4bf0-b89a-be7bc2889c33.png)

**Comment by ndtrongvn** [comment]
#511
