### ISSUE TITLE
[Question] Is it possible to implement this into a script that has captcha on requests? 

### ISSUE THREAD

**Issue by LAD1** [QIN2DIM/hcaptcha-challenger#53]
I have a script that sends requests and I was wondering if there's a simple way to complete the captcha through the request instead of webdriver?

**Comment by LanLan69** [comment]
yo, can I see your script. i can integrate it to requests

**Comment by LAD1** [comment]
> yo, can I see your script. i can integrate it to requests

The script is private unfortunately, if you could maybe show an example request that you would send to discord, I could do it from there

**Comment by Snowad14** [comment]
see https://github.com/Its-Vichy/working-token-gen it uses the response of the captcha in the requests

**Comment by pyrgasm** [comment]
i think what he means is if there's a way he can solve the captcha without actually starting the browser, which there isn't right now its possible tho its probably a little bit complicated to fetch the payload etc...
