### ISSUE TITLE
🥵 lol challenge

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#56]
Perhaps the hcaptcha development team has been working on a blueprint for the next generation of human-machine challenges for some time, but either way, the current boring cat-and-mouse game will only make it more difficult for human visitors and won't do anything for the "smart" robot visitors.

This is actually very boring and even unchallenging.🥵

**Comment by fmcpetermux** [comment]
motorbike_with_watermark?

**Comment by QIN2DIM** [comment]
and seaplane with watermark.😂

**Comment by QIN2DIM** [comment]
But I'm on vacation now.
