### ISSUE TITLE
Planet model release. 

### ISSUE THREAD

**Issue by 3ut** [QIN2DIM/hcaptcha-challenger#561]
New images model.

Download -> [planet.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/11638490/planet.zip)

![Immagine 2023-06-02 220331](https://github.com/QIN2DIM/hcaptcha-challenger/assets/84240761/cc63fb17-be56-4f27-acf1-d78f4e141be7)

**Comment by ndtrongvn** [comment]
Updated new model for this challenge. Thanks @3ut
