### ISSUE TITLE
Model for label motor_vehicle

### ISSUE THREAD

**Issue by TranVinh-13** [QIN2DIM/hcaptcha-challenger#562]
[motor_vehicle.zip](https://github.com/QIN2DIM/hcaptcha-challenger/files/11645585/motor_vehicle.zip)
#https://github.com/RuslanUC/aio-hcaptcha
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/83762343/62586153-bcc6-4499-b1b2-eaf10b17ac80)

**Comment by UnixCr3wR0x** [comment]
did u use an api for it or what ?

**Comment by TranVinh-13** [comment]
@UnixCr3wR0x I use  https://github.com/RuslanUC/aio-hcaptcha for get captcha token
