### ISSUE TITLE
[Challenge] animal

### ISSUE THREAD

**Issue by IamZiroToxic** [QIN2DIM/hcaptcha-challenger#563]
### Prompt[en]

animal

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

discord.com

### Screenshot of the challenge

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/54307278/36190dbf-f6f9-4d70-ad40-fb7bfd2136c3)

**Comment by Vinyzu** [comment]
![grafik](https://github.com/QIN2DIM/hcaptcha-challenger/assets/50874994/8feab4bf-e6e0-4a69-8240-9ca559050707)
Animal Cat
