### ISSUE TITLE
[Question] Challenge structure and some ideia

### ISSUE THREAD

**Issue by lucdias** [QIN2DIM/hcaptcha-challenger#571]
## Brief description

Hello! I hope everything is well! Do you know how many questions can be asked in the hCaptcha challenge? 

My idea is to train a model for each minimal class and search in question if more than one class appears in the challenge. What do you think of this?

Thanks for help!

**Comment by QIN2DIM** [comment]
Realizing logical diversion in neural networks may be a difficult thing. My idea is either fast training for small dataset for special challenges, or training a large model that can cover most extreme cases.

**Comment by QIN2DIM** [comment]
WIP, I will train a YOLOv8 model covering about 300 categories as a fallback for classification tasks. And use it as the first choice for detect and seg tasks.
