### ISSUE TITLE
[*Challenge] Draw a tight bounding box around the X

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#592]
### Prompt[en]

Draw a tight bounding box around the guіtаr.

### New types of challenge

New approach (for ex. image watermark)

### Sitekey

adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

<img width="33%" src="https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/dbe5f4f3-c141-4e35-bbca-e20917408be9.png">

**Comment by QIN2DIM** [comment]
Solved. It looks pretty good ╰(*°▽°*)╯
[a19369cb-ccfe-4821-b4ba-06d287149485.webm](https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/93048d1b-74aa-442e-9c36-d479c1f248b2)

slow mode:
[f43452c5-be91-4845-b189-9399fe1be344.webm](https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/ea2d290d-4333-48bb-a83d-72d19910bf5a)

**Comment by mamadoudelacitenoir** [comment]
hi, how you train models for this type of chall ?

**Comment by QIN2DIM** [comment]
@mamadoudelacitenoir https://github.com/QIN2DIM/hcaptcha-challenger#workflow YOLOv8
