### ISSUE TITLE
[Question] CV2 Import // Update Requirements

### ISSUE THREAD

**Issue by Vinyzu** [QIN2DIM/hcaptcha-challenger#593]
Note that latest opencv version `opencv-python-4.8.0.76` throws error:
`AttributeError: partially initialized module 'cv2' has no attribute 'gapi_wip_gst_GStreamerPipeline' (most likely due to a circular import)`

But stable version `opencv-python-4.5.5.64` throws error:
`ImportError: cannot import name 'Net' from 'cv2.dnn' (unknown location)`

(If you want full errors lmk)
I would generally recommend adding proper requirements because packages like opencv-python can be very version-dependent.
Btw does the new pypi release support new tasks or just new challange types? Would be great if you can also add some more documentation for the pypi release via https://github.com/QIN2DIM/hcaptcha-challenger/issues/577.

**Comment by QIN2DIM** [comment]
> Btw does the new pypi release support new tasks or just new challange types?

not yet I need some time

I will extract the core logic corresponding to `image_label_binary` and `image_label_area_select`, they only deal with tasks related to image classification and object detection ( `keypoint` and `bounding box`) and can run without relying on playwright and selenium.

**Comment by Vinyzu** [comment]
What about the requirements?
Can you provide the opencv-python version you are using?

**Comment by QIN2DIM** [comment]
4.8.0.76

**Comment by Vinyzu** [comment]
> 4.8.0.76

Mh thats weird because i tried this version and it threw the error seen above.
Do you have any idea about this error?

**Comment by QIN2DIM** [comment]
emmmm

I need more error information, and you need to provide a minimal example, otherwise I can't reproduce your case（unless you just import it）。

**Comment by Vinyzu** [comment]
`pip install "opencv-python-headless<4.3"` via [Wav2Lip](https://github.com/Rudrabha/Wav2Lip/issues/387) solved the issue.
Please update the requirements in the new future :D
