### ISSUE TITLE
[Question] there is a problem in your example

### ISSUE THREAD

**Issue by diegoooooooooooooooo** [QIN2DIM/hcaptcha-challenger#595]
I tried the example demo_undetected_playwright.py
this one works well for hcaptcha of this type

![Capture d'écran 2023-08-28 221148](https://github.com/QIN2DIM/hcaptcha-challenger/assets/38768160/cf2b9438-9e0c-43a0-bce7-a5e4e9592805)

but for catcha like these no click is performed

![Capture d'écran 2023-08-28 221057](https://github.com/QIN2DIM/hcaptcha-challenger/assets/38768160/8f6559ef-6c3d-46f5-9553-13176db41b45)

how to fix this? Thank you in advance for your assistance

**Comment by QIN2DIM** [comment]
I'm merging the execution flow of multiple challenges into a common context
-  #591 


contents: `binary challenge`, `keypoint challenge` and `bounding box challenge`

**Comment by diegoooooooooooooooo** [comment]
OK

I just updated your new code and tested that it works without doing anything once in a while, but sometimes you have to click retry once or else it crashes. the crash occurs at the self ._reset_state() function in the control.py file

it's like it doesn't find **getcaptcha**

thank you in advance for your help

**Comment by QIN2DIM** [comment]
> but sometimes you have to click retry once or else it crashes. the crash occurs at the self ._reset_state() function in the control.py file

thanks, I will fix this bug in the next PR
