### ISSUE TITLE
[Question] Where does the HCaptcha Result key come out after it solves? 

### ISSUE THREAD

**Issue by DuckyManBoi** [QIN2DIM/hcaptcha-challenger#60]
I am wondering where the Result after captcha is solved through browser comes to, because I could not find anywhere it doesnt print it or anything. Please help me understand where I get the HCaptcha Result from

**Comment by integragirl** [comment]
module `challenge.py` -> `def runner`
after 
`if resp == challenger.CHALLENGE_SUCCESS:`
add 
`hcaptcha_token = ctx.execute_script('return document.getElementById("hcaptcha-demo").getElementsByTagName("iframe")[0].attributes["data-hcaptcha-response"].value')`

and then add at the end of the function `return hcaptcha_token`
also don't forget to declare a variable `hcaptcha_token` at the beginning of the function

does anyone have any better ideas?

**Comment by shahzain345** [comment]
Well a easier way to do it is:
```py
hcaptcha_token = ctx.execute_script("return hcaptcha.getResponse()")
```

**Comment by vgabs** [comment]
What about tokens after this

`except ChallengePassed:`

Tried both solutions and none of them work
