### ISSUE TITLE
[Question] how to train our own model

### ISSUE THREAD

**Issue by diegoooooooooooooooo** [QIN2DIM/hcaptcha-challenger#600]
Hello I would like to be able to train my own models, is this possible?

If so, could I have the methodology or some ideas on how to do this please?

Thanks in advance

**Comment by QIN2DIM** [comment]
about what? classification or detection

**Comment by diegoooooooooooooooo** [comment]
for the classification it is the onnx model? if that's it I know it's with hcaptcha-model-factory that's what I just found
Besides, I can't do it, that's why I asked a question on the github associate

for detection I would like to know

**Comment by diegoooooooooooooooo** [comment]
@QIN2DIM  can you give me the procedure for training detection models?

thanks in advance

**Comment by QIN2DIM** [comment]
@diegoooooooooooooooo 

This is difficult to make clear. Training YOLO model is a relatively complicated workflow

First of all, you need to collect data sets, adjust the proportion of categories, import pictures on platforms similar to `roboflow`, annotate sample, output datasets, data enhancement, version control/manage, export Train/Val/test data, on the Jupyter platform similar to Google Colab, train.

If you ask how to train. You can run up by a line of code :>

https://docs.ultralytics.com/modes/train/

**Comment by diegoooooooooooooooo** [comment]
Ok thanks I will look into that.

**Comment by QIN2DIM** [comment]
```python
import shutil
from pathlib import Path

from roboflow import Roboflow
from ultralytics import YOLO

project_name = "project-name"
pnv = f"{project_name}-1"

# download dataset
rf = Roboflow(api_key="")
project = rf.workspace("username").project(project_name)
dataset = project.version(1).download("yolov8")

# modify structure
datasets_yolo_dir = Path(f"/content/{pnv}")
dst = Path(f"/content/datasets/{pnv}")
if datasets_yolo_dir.exists() and not dst.exists():
    shutil.move(datasets_yolo_dir, dst)

# train
data_path = dst.joinpath("data.yaml")
model = YOLO("yolov8s.pt")
model.train(data=str(data_path), epochs=300, imgsz=640)

# export to onnx
# YOLO("/content/runs/detect/train/weights/best.pt").export(format="onnx")

# backup model to google-drive
# shutil.copyfile("/content/runs/detect/train/weights/best.onnx", "/content/drive/MyDrive/digit9_yolov8s.onnx")

# deploy to roboflow
# project.version(version).deploy("yolov8", "/content/runs/detect/train/")

```
