### ISSUE TITLE
feat(agent): add built-in coroutine message queue

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#601]
loop and drop mocked XHR response from Playwright

**Comment by Vinyzu** [comment]
Related/Similar to https://github.com/Vinyzu/Botright/blob/main/botright/modules/hcaptcha.py#L84 ?

**Comment by QIN2DIM** [comment]
yes.

**Comment by QIN2DIM** [comment]
Maybe it's time to use an asynchronous interface :>

**Comment by Vinyzu** [comment]
> Maybe it's time to use an asynchronous interface :>

Pleassseee!

**Comment by QIN2DIM** [comment]
fixed by #604 

at [PyPI v0.7.2](https://pypi.org/project/hcaptcha-challenger/#description)
