### ISSUE TITLE
[Question] Can you add living room to the model training code?

### ISSUE THREAD

**Issue by kakapela** [QIN2DIM/hcaptcha-challenger#61]
Challenger not working with captchas where you need to choose living room.
Could you please add living room to the model training code?
![image](https://user-images.githubusercontent.com/34391192/174877135-f25003bd-631b-4b5d-a3eb-8c1d843a60d0.png)

**Comment by QIN2DIM** [comment]
site key

**Comment by QIN2DIM** [comment]
Interesting classification tasks
![Suggestion](https://user-images.githubusercontent.com/62018067/174934560-25c4148a-ab3e-406d-bb60-c4fa934dac14.gif)
