### ISSUE TITLE
feat(add): New type of "Car"

### ISSUE THREAD

**Issue by bitcoinautomatic** [QIN2DIM/hcaptcha-challenger#63]
Will car be added?

**Comment by QIN2DIM** [comment]
site key

**Comment by bitcoinautomatic** [comment]
322e5e22-3542-4638-b621-fa06db098460
rambler.ru

**Comment by bitcoinautomatic** [comment]
> site key

322e5e22-3542-4638-b621-fa06db098460
rambler.ru

**Comment by QIN2DIM** [comment]
I am unable to reproduce this challenge, can you please provide a screenshot of the challenge？

**Comment by bitcoinautomatic** [comment]
> I am unable to reproduce this challenge, can you please provide a screenshot of the challenge？
![Screenshot_20220627-175009_Discord](https://user-images.githubusercontent.com/102923440/175970162-c421d210-cf01-433a-9f10-64b0f5622dc3.png)

**Comment by ijnrghjkdsmigywneig203** [comment]
Using the yolov6n model can detect the cars. Fix

**Comment by ijnrghjkdsmigywneig203** [comment]
Also, adding a human like curve to click the captcha element would be a good idea as well, this would also help with reducing the chance of bot detection.

**Comment by QIN2DIM** [comment]
> Currently it's solving way too fast and ...

really?😂 I think you can do it yourself. It's not that hard.

> ... curve ...

pending feat

**Comment by ijnrghjkdsmigywneig203** [comment]
> @ijnrghjkdsmigywneig203
> 
> > Currently it's solving way too fast and ...
> 
> really?😂 I think you can do it yourself. It's not that hard.
> 
> > ... curve ...
> 
> pending feat

already did :)

**Comment by QIN2DIM** [comment]
If you simply want to slow it down, it is very naive to use `sleep()` blindly; you should go with the slightly slower but more accurate yolo model.

**Comment by ijnrghjkdsmigywneig203** [comment]
> If you simply want to slow it down, it is very naive to use `sleep()` blindly; you should go with the slightly slower but more accurate yolo model.

I tried that, was still too fast and didnt detect cars. Now using the yolov6 model and it's working pretty good, I did use time.sleep but made it so it would choose a random number from 3.5495890 - 6.90840985 for example.

**Comment by Curlypla** [comment]
We understand you are the best programmer and we can't compare to you but try to be more friendly please

**Comment by ijnrghjkdsmigywneig203** [comment]
> We understand you are the best programmer and we can't compare to you but try to be more friendly please

I agree.

**Comment by QIN2DIM** [comment]
> We understand you are the best programmer and we can't compare to you but try to be more friendly please

I'm not the best programmer. I will not be stingy to share knowledge, but I firmly draw a line with "Underground Industry".

( ~Most of my replies are machine translated using DeepL - - seems a bit odd in tone. 👀~

**Comment by Curlypla** [comment]
> > We understand you are the best programmer and we can't compare to you but try to be more friendly please
> 
> I'm not the best programmer. I will not be stingy to share knowledge, but I firmly draw a line with "Underground Industry".
> 
> ( ~Most of my replies are machine translated using DeepL - - seems a bit odd in tone. 👀~

Bruh I was talking about ijnrghjkdsmigywneig203 xd

**Comment by ijnrghjkdsmigywneig203** [comment]
> > > We understand you are the best programmer and we can't compare to you but try to be more friendly please
> > 
> > 
> > I'm not the best programmer. I will not be stingy to share knowledge, but I firmly draw a line with "Underground Industry".
> > ( ~Most of my replies are machine translated using DeepL - - seems a bit odd in tone. 👀~
> 
> Bruh I was talking about ijnrghjkdsmigywneig203 xd

Sorry?
