### ISSUE TITLE
[Question] Using YoloChallenger

### ISSUE THREAD

**Issue by Vinyzu** [QIN2DIM/hcaptcha-challenger#637]
Lets say i wanna use the yolov8 feature of the challenger like to detect a `Bus` object:
```py
import hcaptcha_challenger as solver

# Init local-side of the ModelHub
solver.install()

prompt = "bus"

def bytedance():
	classifier = solver.BinaryClassifier()
	result = classifier.execute(prompt, ["image_placeholder"])
	print(result)


if __name__ == "__main__":
	bytedance()
```
The Objects.yaml file would suggest that this is possible: [objects.yaml](https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/objects.yaml#L15)

But i get `2023-09-06 18:42:28 | DEBUG - Types of challenges not yet scheduled - {'label': 'bus', 'prompt': 'bus'}`

**Comment by QIN2DIM** [comment]
emmm I remember we discussed this

https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/examples/demo_detect.py

**Comment by Vinyzu** [comment]
I basicly just want to classify so yes/no per image

**Comment by QIN2DIM** [comment]
That's the same，`demo_detect.py` can do binary tasks, you just need to determine if there is a 'bus' in the return result.
