### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by AreYouMehmetEfeisModder** [QIN2DIM/hcaptcha-challenger#644]
In the pypi training, which is really hard to understand, you say run main.py in src, but there is no such thing, and also it would be very nice to do it as an api, we could run it with codespaces and the training is not understood, even if there are no files you said, where is the training?

**Comment by AreYouMehmetEfeisModder** [comment]
for token gen maybe api be like capsolver self use proxy and more

**Comment by AreYouMehmetEfeisModder** [comment]
thanks

**Comment by AreYouMehmetEfeisModder** [comment]
I just saw that you wrote a new documentation, when will it be published?

**Comment by QIN2DIM** [comment]
what's the `main.py`? Where did you read the documentation 😮

**Comment by AreYouMehmetEfeisModder** [comment]
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/88922637/c50b6c2d-4496-439e-9f88-579bb2c8ff68)

**Comment by AreYouMehmetEfeisModder** [comment]
when will the new document come and do you plan to make the usage code as api like capsolver solve(api_key host sitekey proxy) api would be very nice if there is already very few with api on github

**Comment by AreYouMehmetEfeisModder** [comment]
and how can I train the models do I need to train already ready model is enough

**Comment by AreYouMehmetEfeisModder** [comment]
@QIN2DIM

**Comment by QIN2DIM** [comment]
emmmmm

https://github.com/QIN2DIM/hcaptcha-challenger/wiki/Get-started-%E2%80%90-Library

**Comment by QIN2DIM** [comment]
> ![image](https://user-images.githubusercontent.com/88922637/266799914-c50b6c2d-4496-439e-9f88-579bb2c8ff68.png)

I mean, this file you're looking at is outdated. I deleted it a long time ago. Where did you find it...

The latest documentation is on the wiki

**Comment by AreYouMehmetEfeisModder** [comment]
can be found from pypi look at the first versions xd old wiki
When I say api, I mean to host and use it somewhere, whether it works with the document you are throwing now or whether it is the current tutorial is not very clear xd

**Comment by AreYouMehmetEfeisModder** [comment]
If I run the py files in examples, will it solve the demo captcha with chrome dirver? 
Usage
Once installed, you can import hcaptcha_challenger in a Python script, and call any of the 2 AI components (Classifier, AreaSelector).

you wrote this, but we write the promt part in the code, then it is not automatic

**Comment by AreYouMehmetEfeisModder** [comment]
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples> py demo_undetected_playwright.py
2023-09-10 05:00:05 | DEBUG - Downloading resource - {'url': 'https://raw.githubusercontent.com/QIN2DIM/hcaptcha-challenger/main/src/objects.yaml', 'to': 'C:\\Users\\MehmetEfeFriday\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\hcaptcha_challenger\\onnx\\models\\objects.yaml'}
2023-09-10 05:00:07 | INFO - Reloading the local cache of Assets - {'assets_dir': 'C:\\Users\\MehmetEfeFriday\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\hcaptcha_challenger\\onnx\\models\\_assets'}
2023-09-10 05:00:07 | DEBUG - Pulling Assets index file - {'url': 'https://api.github.com/repos/QIN2DIM/hcaptcha-challenger/releases'}
Traceback (most recent call last):
  File "C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples\demo_undetected_playwright.py", line 62, in <module>
    asyncio.run(bytedance())
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples\demo_undetected_playwright.py", line 57, in bytedance
    await malenia.execute(sequence=[hit_challenge], headless=False)
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\site-packages\hcaptcha_challenger\agents\playwright\tarnished.py", line 144, in execute
    context = await p.firefox.launch_persistent_context(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\async_api\_generated.py", line 14926, in launch_persistent_context
    await self._impl_obj.launch_persistent_context(
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_browser_type.py", line 158, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 61, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 482, in wrap_api_call
    return await cb()
           ^^^^^^^^^^
  File "C:\Users\MehmetEfeFriday\AppData\Local\Programs\Python\Python311\Lib\site-packages\playwright\_impl\_connection.py", line 97, in inner_send
    result = next(iter(done)).result()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
playwright._impl._api_types.Error: Executable doesn't exist at C:\Users\MehmetEfeFriday\AppData\Local\ms-playwright\firefox-1422\firefox\firefox.exe
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples>

**Comment by AreYouMehmetEfeisModder** [comment]
i get same all

PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples> ls


    Directory: C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10.09.2023     04:56                diamond_bracelet
d-----        10.09.2023     04:56                image_label_area_select
d-----        10.09.2023     04:56                motion
d-----        10.09.2023     05:00                user_data_dir
-a----        10.09.2023     04:56            722 demo_classify.py
-a----        10.09.2023     04:56           1252 demo_detect.py
-a----        10.09.2023     04:56            298 demo_install.py
-a----        10.09.2023     04:56           1772 demo_normal_playwright.py
-a----        10.09.2023     04:56           2032 demo_undetected_playwright.py


PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples> py demo_classify.py
Challenge Image 1.png - True
Challenge Image 2.png - False
Challenge Image 3.png - False
Challenge Image 4.png - False
Challenge Image 5.png - False
Challenge Image 6.png - False
Challenge Image 7.png - False
Challenge Image 8.png - True
Challenge Image 9.png - True
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples>

**Comment by QIN2DIM** [comment]
If you need to run a demo other than classify and detect：

```bash
pip install -U hcaptcha-challenger[playwright] 
playwright install
playwright install-deps
```

**Comment by QIN2DIM** [comment]
I have abandoned my support for selenium. I have a bias for high-performance systems )

**Comment by AreYouMehmetEfeisModder** [comment]
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/88922637/f6272448-397f-4435-b2c1-e66d6facf569)

**Comment by AreYouMehmetEfeisModder** [comment]
i updated xd
what do I need to use for captcha solve which function you need to call and site key host and proxy I need to write into that function

**Comment by AreYouMehmetEfeisModder** [comment]
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/88922637/49d2874e-cbd6-42cc-9f12-122491f49551)
yes it worked is there a power usage between undetected and detected nighly I think it uses more and how I will use it for example discord to solve the captcha on a site for example is there a call function that I can put the sitekey and host and is there a proxy feature

**Comment by AreYouMehmetEfeisModder** [comment]
worked now but now i get this error from this
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples> py demo_detect.py
2023-09-10 06:13:50 | ERROR - ModelNotFound, please upgrade assets and flush yolo model - {'focus_name': 'animal0831_yolov8s.onnx'}
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples>

**Comment by AreYouMehmetEfeisModder** [comment]
demo_detect.py and demo_classify.py what is their function what do they do 
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples> py demo_detect.py
2023-09-10 06:16:10 | DEBUG - Downloading resource - {'url': 'https://github.com/QIN2DIM/hcaptcha-challenger/releases/download/model/animal0831_yolov8s.onnx', 'to': 'C:\\Users\\MehmetEfeFriday\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\hcaptcha_challenger\\onnx\\models\\animal0831_yolov8s.onnx'}
raccoon.1.png - class_name='raccoon' (center_x, center_y)=(199, 164)
raccoon.2.png - class_name='raccoon' (center_x, center_y)=(108, 182)
raccoon.3.png - class_name='raccoon' (center_x, center_y)=(135, 117)
raccoon.4.png - class_name='raccoon' (center_x, center_y)=(205, 166)
raccoon.5.png - class_name='raccoon' (center_x, center_y)=(141, 42)
raccoon.6.png - class_name='raccoon' (center_x, center_y)=(127, 48)
raccoon.7.png - class_name='raccoon' (center_x, center_y)=(80, 151)
raccoon.8.png - class_name='raccoon' (center_x, center_y)=(50, 51)
raccoon.9.png - class_name='raccoon' (center_x, center_y)=(195, 130)
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples> py demo_classify.py
Challenge Image 1.png - True
Challenge Image 2.png - False
Challenge Image 3.png - False
Challenge Image 4.png - False
Challenge Image 5.png - False
Challenge Image 6.png - False
Challenge Image 7.png - False
Challenge Image 8.png - True
Challenge Image 9.png - True
PS C:\Users\MehmetEfeFriday\Desktop\Projects\Project16HCAPTCHASOLVER\hcaptcha-challenger\examples>

**Comment by AreYouMehmetEfeisModder** [comment]
how can i get a captcha key to use after solving the captcha example discord account generator

**Comment by AreYouMehmetEfeisModder** [comment]
@QIN2DIM

**Comment by AreYouMehmetEfeisModder** [comment]
hey? @QIN2DIM

**Comment by AreYouMehmetEfeisModder** [comment]
how to get token for dc token gen example

**Comment by AreYouMehmetEfeisModder** [comment]
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/88922637/c49c25ed-c445-485e-b463-45825c03e8ed)
discord not work

**Comment by AreYouMehmetEfeisModder** [comment]
how to make origin and referer

**Comment by AreYouMehmetEfeisModder** [comment]
@QIN2DIM

**Comment by QIN2DIM** [comment]
I dont know 😅

**Comment by AreYouMehmetEfeisModder** [comment]
ok bye thx every day you install new objects for new models, do I need to use demo_install.py to update them?

**Comment by AreYouMehmetEfeisModder** [comment]
@QIN2DIM
