### ISSUE TITLE
[Challenge] Please click on the head of the animal

### ISSUE THREAD

**Issue by Lefeus** [QIN2DIM/hcaptcha-challenger#651]
### Prompt[en]

Please click on the head of the animal

### New types of challenge

Please click on the head of the animal

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Screenshot of the challenge

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/111588764/bc83317e-f6fe-4289-919c-4fda311d18a9)
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/111588764/3cacee9a-eda5-4465-9a57-c76f775195f9)

**Comment by QIN2DIM** [comment]
cat, cow, horse, panda
