### ISSUE TITLE
[Challenge] Domestic Cat

### ISSUE THREAD

**Issue by LanLan69** [QIN2DIM/hcaptcha-challenger#68]
### Prompt[en]

Please click each image containing a domestic cat

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Screenshot of the challenge

<img width="481" alt="2022-07-11_17 33 06" src="https://user-images.githubusercontent.com/91493509/178364508-165c2feb-78d9-4831-997c-81e191abfedc.png">

**Comment by QIN2DIM** [comment]
so cute
