### ISSUE TITLE
[Question] How can I contribute

### ISSUE THREAD

**Issue by autojadame** [QIN2DIM/hcaptcha-challenger#682]
Hello! I love the work that you are doing and I would want to know how can I help with the challenges model training. I know you got a collector to run on the website that the challengens are reported, I guess i need to take that images and select the part of the image and pass it to the model for training, but would be nice if you can place some docs to being able to help you.

Thank you very much

**Comment by QIN2DIM** [comment]
Before I started this project, I thought training models would be both challenging and valuable.

However, now I feel that "training models" is a physical rather than mental effort, a waste of time and pointless, and if someone is willing to do it, that's fine.🥹

**Comment by QIN2DIM** [comment]
So I had to automate all this worthless stuff, and it worked fine. But now I also feel that labeling data is a waste of time.🥹

**Comment by QIN2DIM** [comment]
funcaptcha，hcaptcha，recaptcha or other products. Borrowed are the most basic CV tasks, there is no possibility of stopping the robot. But they can easily disrupt the mood of users who want to visit a website normally.😴

**Comment by QIN2DIM** [comment]
documentation WIP

**Comment by autojadame** [comment]
Thank you very much

**Comment by autojadame** [comment]
I know it's a pain in the ass, but becuase i appreciate it, i would want to help you a bit
