### ISSUE TITLE
[Question] Airplane flying left

### ISSUE THREAD

**Issue by adv-zl** [QIN2DIM/hcaptcha-challenger#7]
![image](https://user-images.githubusercontent.com/16443377/156515635-c240a133-7261-4167-8091-9d1ca72d7b37.png)
Discord added new type of captchas. Any solutions how to solve it?

**Comment by QIN2DIM** [comment]
Yes, I have collected enough [datasets](https://github.com/QIN2DIM/img_pool/releases/tag/airplane_in_the_sky_flying_left). 

I am working on a higher precision fitting method and I will push up a new solution in the near future
