### ISSUE TITLE
[Challenge] Lion without mane/ Lion with mane on its neck

### ISSUE THREAD

**Issue by kakapela** [QIN2DIM/hcaptcha-challenger#71]
### Prompt[en]

Please click each image containing a lion without mane
Please click each image containing a lion with mane on its neck

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

![ex1](https://user-images.githubusercontent.com/34391192/178578029-1d36aaca-f01f-4e84-8715-6a527bb5b9dd.JPG)
![exx1](https://user-images.githubusercontent.com/34391192/178578166-669900c7-04cf-4f2f-b91f-1c98f5ab0ba4.JPG)
![exx3](https://user-images.githubusercontent.com/34391192/178578195-3a49ae18-72a4-4231-9c29-284227216279.JPG)

**Comment by QIN2DIM** [comment]
Can't be reproduced for now

**Comment by kakapela** [comment]
Yes, I also can't reproduced it as for now. Maybe the lion challenge appears on specific time. Anyway I've noticed that images with lions also appears when you have to click images with a domestic cat.  Maybe that info will help you somehow. Greets.

**Comment by mevichi** [comment]
@QIN2DIM I can reproduce it right now, every single time.

![image](https://user-images.githubusercontent.com/104154524/179009603-3b895bd0-4234-4e54-badb-fef3f06783da.png)

**Comment by QIN2DIM** [comment]
@mevichi Please resubmit the issue
