### ISSUE TITLE
[Challenge] Bridge

### ISSUE THREAD

**Issue by kakapela** [QIN2DIM/hcaptcha-challenger#72]
### Prompt[en]

Please click each image containing a bridge

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=adafb813-8b5c-473f-9de3-485b4ad5aa09

### Screenshot of the challenge

![exam1](https://user-images.githubusercontent.com/34391192/178785661-78908819-9661-4bca-95c2-dc3a11fce901.JPG)
![exam2](https://user-images.githubusercontent.com/34391192/178785664-7c919525-6906-4d52-963e-078f5f1c600b.JPG)
![exam3](https://user-images.githubusercontent.com/34391192/178785677-8259ffb2-4ab3-4c46-a230-29795994dd11.JPG)

**Comment by SpotnikSignal** [comment]
Jup got the same one, hope to see it added ^^ also let me take this moment to say how awesome this project is, is it working really well! I've been puzzling with the script to add custom form input, proxy functionality and also added a custom javascript inject part.
Also the code is very clean and well written, good job ^^

**Comment by kakapela** [comment]
If you won't be able to reproduce this challenge I have prepared for you bridges dataset collected from challenges that I came across. Images was downloaded using your code (they are  coming from /src/database/temp_cache/_challenge dir).
I've left only images with bridges. Link to download bridges dataset: [https://easyupload.io/6aimk6](https://easyupload.io/6aimk6)
Greets.

**Comment by QIN2DIM** [comment]
@kakapela @SpotnikSignal Thank you for your support of this project. 🥂

**Comment by QIN2DIM** [comment]
@kakapela Anyway thanks for your work, we will update the new pluggable model out later.👻

**Comment by SpotnikSignal** [comment]
@QIN2DIM @kakapela thanks guys, working perfectly again!
