### ISSUE TITLE
[Challenge] Please click each image containing an DOG

### ISSUE THREAD

**Issue by deepakkumar132** [QIN2DIM/hcaptcha-challenger#741]
### Prompt[en]

 Please click each image containing an dog

### request_type

image_label_binary (for ex. Please click each image containing a fox)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=discord

### Screenshot of the challenge

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/91746542/08b2ca3d-2b36-4646-b228-e69e5367b6d5)

**Comment by QIN2DIM** [comment]
btw, discord's sitekey is `f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34`? or switch to `4c672d35-0701-42b2-88c3-78380b0db560`
