### ISSUE TITLE
[Challenge]  PLEASE CLICK ON THE THUMBNAIL OF SOMETHING THAT CAN BE EATEN

### ISSUE THREAD

**Issue by deepakkumar132** [QIN2DIM/hcaptcha-challenger#748]
### Prompt[en]

 PLEASE CLICK ON THE THUMBNAIL OF SOMETHING THAT CAN BE EATEN

### request_type

image_label_area_select: point (fox ex. Please click on the X)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=discord.com

### Screenshot of the challenge

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/91746542/dd222e28-fe14-4e78-bba0-d683f121a3e8)

**Comment by QIN2DIM** [comment]
dup of #725

**Comment by QIN2DIM** [comment]
I didn't write the changelog, anyway you need to update the pypi package to handle this challenge, I changed the source code.

```
pip install -U hcaptcha-challenger[playwright]
```
