### ISSUE TITLE
Demo undetected playwright doesn't extract the result when the challenge box doesn't appear.

### ISSUE THREAD

**Issue by tarekwiz** [QIN2DIM/hcaptcha-challenger#766]
As the title describes. Demo undetected playwright doesn't extract the result when the challenge box doesn't appear.

Sitekey for reference: sitekey = "a010c060-9eb5-498c-a7b9-9204c881f9dc"

It just says 
`>> 1 - Challenge Result: success
View RQdata path=None`

**Comment by QIN2DIM** [comment]
Can you provide the complete log? I want to see the time of each step operation.

`/path/to/hcaptcha-challenger[main]/hcaptcha-llenger/logs/runtime.log`

**Comment by tarekwiz** [comment]
`2023-10-01 17:31:59 | DEBUG    | hcaptcha_challenger.onnx.modelhub:request_resource:46 | Downloading resource - {'url': 'https://raw.githubusercontent.com/QIN2DIM/hcaptcha-challenger/main/src/objects.yam$
2023-10-01 17:31:59 | INFO    | hcaptcha_challenger.onnx.modelhub:flush_runtime_assets:137 | Reloading the local cache of Assets - {'assets_dir': '/Users/tarekadel/hcaptcha-challenger/hcaptcha_challenger$
2023-10-01 17:31:59 | DEBUG    | hcaptcha_challenger.onnx.modelhub:flush_runtime_assets:151 | Pulling Assets index file - {'url': 'https://api.github.com/repos/QIN2DIM/hcaptcha-challenger/releases'}
2023-10-01 17:32:03 | INFO    | hcaptcha_challenger.agents.playwright.tarnished:execute:158 | Execute task - {'name': 'hit_challenge'}

`

**Comment by QIN2DIM** [comment]
ok, Execute task - {'name': 'hit_challenge'} After this, does the program exit immediately or does it standstill for a while before print()

**Comment by tarekwiz** [comment]
It waits till it shows the success on the playwright browser then it closes. I debugged it turns out in the file hcaptcha_challenger/agents/playwright/control.py Line 236
 ``async def handler(self, response: Response):``
 
 The issue is in this function because "https://hcaptcha.com/getcaptcha/" can also return a ChallengeResp if there is no challenge and that case is not handled

**Comment by QIN2DIM** [comment]
check this 

https://github.com/QIN2DIM/hcaptcha-challenger/pull/767/files

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/384ad654-e0f3-4c12-91a9-267874877f3e)

**Comment by QIN2DIM** [comment]
Because 'self._reset_state()' is executed after each challenge starts, it clears challenges eresp.

https://github.com/QIN2DIM/hcaptcha-challenger/blob/2a8d4f603e2a68ae80153edf1cb5f21753cfd932/hcaptcha_challenger/agents/playwright/control.py#L571

**Comment by tarekwiz** [comment]
Yeah that still doesn't work. rqdata_path is null even after ``await agent.handle_checkbox()``

**Comment by QIN2DIM** [comment]
emmm I think the logic after the change is like this

```mermaid
flowchart LR

start("agent.handle_checkbox()")
done{"Success?"}
return("agent.export_rq() and return")
challenge("agent.execute()")

start --> done
done -- "yes" --- return
done -- "no" --- challenge
challenge --> done
```

**Comment by tarekwiz** [comment]
export_rq() only works if self.cr in control.py is set, which is never set idk why.

**Comment by QIN2DIM** [comment]
oh I know -.-

**Comment by tarekwiz** [comment]
Changing the handler to this fixed it. (Also includes the solution you mentioned above)

```
    async def handler(self, response: Response):
        if response.url.startswith("https://hcaptcha.com/getcaptcha/"):
            with suppress(Exception):
                data = await response.json()
                if data["pass"] == True:
                    cr = ChallengeResp.from_json(data)
                    self.cr = cr
                else:
                    qr = QuestionResp.from_json(data)
                    qr.save_example(tmp_dir=self.record_json_dir)
                    self.qr_queue.put_nowait(qr)
        if response.url.startswith("https://hcaptcha.com/checkcaptcha/"):
            with suppress(Exception):
                metadata = await response.json()
                cr = ChallengeResp.from_json(metadata)
                self.cr_queue.put_nowait(cr)```

**Comment by tarekwiz** [comment]
But I don't think this is the optimal solution because I have to add ``await page.wait_for_timeout(5000)`` before checking which is not the best

**Comment by QIN2DIM** [comment]
check this

https://github.com/QIN2DIM/hcaptcha-challenger/pull/767/files

I only modified it in the demo


![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/6bd6aa4e-b019-4b0e-9fc0-68a6ae8fd126)

**Comment by tarekwiz** [comment]
> check this
> 
> https://github.com/QIN2DIM/hcaptcha-challenger/pull/767/files
> 
> I only modified it in the demo
> 
> ![image](https://user-images.githubusercontent.com/62018067/271837225-6bd6aa4e-b019-4b0e-9fc0-68a6ae8fd126.png)

This works but have to change control.py L236 to this

```
    async def handler(self, response: Response):
        if response.url.startswith("https://hcaptcha.com/getcaptcha/"):
            with suppress(Exception):
                data = await response.json()
                if "pass" in data and data["pass"] == True:
                    cr = ChallengeResp.from_json(data)
                    self.cr_queue.put_nowait(cr)
                else:
                    qr = QuestionResp.from_json(data)
                    qr.save_example(tmp_dir=self.record_json_dir)
                    self.qr_queue.put_nowait(qr)
        if response.url.startswith("https://hcaptcha.com/checkcaptcha/"):
            with suppress(Exception):
                metadata = await response.json()
                cr = ChallengeResp.from_json(metadata)
                self.cr_queue.put_nowait(cr)
                
              ```

And add this ``    await page.wait_for_timeout(5000)`` before ```    if not agent.cr_queue.empty():
        cr = agent.cr_queue.get_nowait()
        if cr.is_pass:
            agent.cr = cr
            rqdata_path = agent.export_rq()
            print(f"View RQdata path={rqdata_path}")
            return rqdata_path
```

**Comment by QIN2DIM** [comment]
By the way =. = How do you improve the pass rate after handle_checkbox, almost all the tests on my side will pop up challenges. 😅(I can hardly come up with this problem)

**Comment by tarekwiz** [comment]
I think it's because I'm on a Mac

**Comment by QIN2DIM** [comment]
You mean, after Handle Checkbox, if the challenge passes, the `is_pass` field will return from` Getcaptcha` instead of `Checkcaptcha`?
```python
    async def handler(self, response: Response):
        if response.url.startswith("https://hcaptcha.com/getcaptcha/"):
            with suppress(Exception):
                data = await response.json()
                if "pass" in data and data["pass"] == True:
                    cr = ChallengeResp.from_json(data)
                    self.cr_queue.put_nowait(cr)
                else:
                    qr = QuestionResp.from_json(data)
                    qr.save_example(tmp_dir=self.record_json_dir)
                    self.qr_queue.put_nowait(qr)
        if response.url.startswith("https://hcaptcha.com/checkcaptcha/"):
            with suppress(Exception):
                metadata = await response.json()
                cr = ChallengeResp.from_json(metadata)
                self.cr_queue.put_nowait(cr)
```

**Comment by tarekwiz** [comment]
Yes exactly! Maybe we should fix how reset_state works and how the self.cr is set and that should fix it?

**Comment by QIN2DIM** [comment]
emm, can you provide the response dataForm 

 I think I need to update the QuestionResp dataclass

**Comment by tarekwiz** [comment]
This is the response that I get

<img width="731" alt="Screenshot 2023-10-01 at 6 55 10 PM" src="https://github.com/QIN2DIM/hcaptcha-challenger/assets/5272589/b5c53ef6-486a-4095-8372-a5e599e21338">

**Comment by QIN2DIM** [comment]
emmm I think the original code covered this because I checked the qr field after reset_state(). If the challenge is skipped after handle_checkbox(), then the following statement is executed, which immediately returns STATE.SUCCESS.

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/888ef856-6fb2-431d-9d92-35655a647df8)

**Comment by tarekwiz** [comment]
Yeah it returns success but never sets the self.cr to the right one

**Comment by QIN2DIM** [comment]
As you said earlier, the Handle_checkbox() success STATE is not actually cleared by reset_state(), so we can still get the "response" at return state.success.

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/fb319598-6c13-41d5-9849-b154d488a559)

**Comment by QIN2DIM** [comment]
it's self.qr actually😅

**Comment by QIN2DIM** [comment]
But I seem to have filtered out unexpected key-value pairs

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/62018067/60d5c16c-119f-4e48-95b0-45ce41db37d0)

**Comment by tarekwiz** [comment]
Not sure what you mean to be honest

**Comment by tarekwiz** [comment]
Ok I get it now, maybe we should improve the handler function itself and how the `return state.success` works

**Comment by tarekwiz** [comment]
Ok so I figured out how to fix it. Gonna open a pull request now.
