### ISSUE TITLE
[Challenge] steak

### ISSUE THREAD

**Issue by deepakkumar132** [QIN2DIM/hcaptcha-challenger#772]
### Prompt[en]

Please click each image containing a steak

### request_type

image_label_binary (for ex. Please click each image containing a fox)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=discord.com

### Screenshot of the challenge

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/91746542/b94e8361-6b41-4b8e-b9ae-e100a2722747)

**Comment by QIN2DIM** [comment]
duf of #773
