### ISSUE TITLE
Weird prompt/label

### ISSUE THREAD

**Issue by Lefeus** [QIN2DIM/hcaptcha-challenger#793]
Why this model is not supported?

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/111588764/833a023c-b8be-4429-b69a-fccecb4c53ce)

**Comment by QIN2DIM** [comment]
btw I set up a number of layers of policies to handle binary-challenge model synchronization issues.

This warning log appears, indicating that either you did not run 'solver.install(upgrade=True)' before running, or you used code from another branch (i.e., only the core business module was selected and the branch of the environment inspection module was discarded).

**Comment by Lefeus** [comment]
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/111588764/ed55bcc8-738e-4b42-8b25-c1c82c1fd1f8)
 just fixed thank you very much

**Comment by QIN2DIM** [comment]
I suggest you use the "policy" as well...

They validate the model cache to avoid duplicate downloads.
