### ISSUE TITLE
Slow image recognition.

### ISSUE THREAD

**Issue by Its-Vichy** [QIN2DIM/hcaptcha-challenger#80]
Since the bedroom challenge, the image recognition is really slow.
I have no idea if this is a problem or if it's from a difficult function.

(If this is the only function that aims to detect something about chambers, lions or whatever, I think it would be nice not to run this function on
mortorbuss and other easy captchas)

**Comment by QIN2DIM** [comment]
`python main.py install`

**Comment by Its-Vichy** [comment]
That is not the problem, the solver can solve without problem litle amount of images but if we are recognizing somes more that take +1m to recognize

**Comment by QIN2DIM** [comment]
What I mean is that if you intend to provide a fee-based service to another group of people through open source technology, you should have the ability to make improvements accordingly.

**Comment by Its-Vichy** [comment]
The problem is not there, it is that there is an obvious difference between the two versions
