### ISSUE TITLE
[Challenge] elephant with long tusk

### ISSUE THREAD

**Issue by LanLan69** [QIN2DIM/hcaptcha-challenger#83]
### Prompt[en]

Please click each elephant containing a long musk

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

<img width="397" alt="截屏2022-07-15 16 46 54" src="https://user-images.githubusercontent.com/91493509/179308393-77bc8c2f-d14d-483c-ba50-685aeec0e87c.png">

**Comment by QIN2DIM** [comment]
ok，还有个“小象”的 prompt ，再发个issue
