### ISSUE TITLE
[Q&A] How to use nested categories

### ISSUE THREAD

**Issue by pawssx** [QIN2DIM/hcaptcha-challenger#835]
## Brief description

Hi! i have problem while running nested prompt: "Please click on the largest animal." I can see they have .onyx models and they are in objects.yaml but i dont now how to run it propertly.I use demo_classify.py from examples. I would be grateful for any help. 

## Error

```markdown
2023-10-15 18:39:56 | DEBUG - Types of challenges not yet scheduled - {'label': 'please click on the largest animal', 'prompt': 'Please click on the largest animal.'}
```

**Comment by QIN2DIM** [comment]
upgrade to latest version v0.8.7 ++

**Comment by pawssx** [comment]
I tried version 0.8.7, 0.8.7-post1 and `pip install -U hcaptcha-challenger[playwright]` all with `install(upgrade=True)` but still im getting same error `2023-10-15 19:08:08 | DEBUG - Types of challenges not yet scheduled - {'label': 'please click on the largest animal', 'prompt': 'Please click on the largest animal.'}`

**Comment by QIN2DIM** [comment]
How do you use it 0.0

**Comment by QIN2DIM** [comment]
fine, I didn't export this feat as an example. If you do not use it in the context of AgentT, you cannot activate trigger this feature.

'nested categories' needs to provide an' example image 'and a' challenge prompt 'to filter and sort models, and then select the best model to do the second processing of' challenge images'.

**Comment by pawssx** [comment]
So what would I have to change in demo_classify.py to make it work? I'm too stupid to understand how it works exactly. I would be very grateful for your help.

**Comment by vxrip** [comment]
ye i have the same problem

**Comment by QIN2DIM** [comment]
@pawssx  @vxrip  So what I'm saying is, how do you use this program, I can just wrap a high-level interface.

**Comment by pawssx** [comment]
Im currently using demo_classify.py: `# -*- coding: utf-8 -*-
# Time       : 2022/9/23 17:28
# Author     : QIN2DIM
# Github     : https://github.com/QIN2DIM
# Description:
import os
from pathlib import Path

import hcaptcha_challenger as solver

# Init local-side of the ModelHub
solver.install(upgrade=True)

prompt = "diamond bracelet"

label_dir = Path(__file__).parent.joinpath("diamond_bracelet")

images = [label_dir.joinpath(fn).read_bytes() for fn in os.listdir(label_dir)]


def bytedance():
    classifier = solver.BinaryClassifier()
    if result := classifier.execute(prompt, images):
        for i, name in enumerate(os.listdir(label_dir)):
            print(f"{name} - {result[i]}")


if __name__ == "__main__":
    bytedance()
`

But if nested categories dont work on this code i can switch to anything but without selenium and as always i will be very grateful for help

**Comment by QIN2DIM** [comment]
I mean, how did you import hcaptcha_challenger and use it in your project.

It's impossible to just run this example, right?😅

**Comment by pawssx** [comment]
Im using hcaptcha challenger literally same as demo_classify code here: `
import os, json
from pathlib import Path
import time
import hcaptcha_challenger as solver

solver.install(flush_yolo=True, upgrade=True)

    def solvecapclas(prompt: str, path: str):
        cap_prompt = prompt
        label_dir = Path(__file__).parent.joinpath("solverdata", "classify", path)
        images = [label_dir.joinpath(fn).read_bytes() for fn in os.listdir(label_dir)]

        classifier = solver.BinaryClassifier()

      
        if result := classifier.execute(cap_prompt, images):

            answers1 = {
                name[:-5]: result[i]
                for i, name in enumerate(os.listdir(label_dir))
            }
            return json.dumps(answers1)
`
Im getting all the images from request. I want to notice that from that from that same request i can get example_question soo it would be possible to specify a .onyx model without selenium but im not too smart to do this

**Comment by QIN2DIM** [comment]
emmmm......

This looks like it's just a change to the example code.

**Comment by pawssx** [comment]
its literally 1:1 thats why im asking if its possible that you could help me or do a new example i was thinking about separate .onyx model that will match example images

**Comment by QIN2DIM** [comment]
Your requirement is too simple, I changed some of the code of classifier, you only need to pass one more parameter.
