### ISSUE TITLE
 [Challenge] Horse

### ISSUE THREAD

**Issue by LanLan69** [QIN2DIM/hcaptcha-challenger#85]
### Prompt[en]

Please click each image containing a horse

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=4c672d35-0701-42b2-88c3-78380b0db560

### Screenshot of the challenge

<img width="395" alt="截屏2022-07-15 17 22 12" src="https://user-images.githubusercontent.com/91493509/179312632-6e8ba1c8-c9d0-4b9a-9daf-35d968de80f1.png">
对不起啊大哥，我今天找到好多个新的

**Comment by QIN2DIM** [comment]
可以方便透露一下sitekey对应的站点吗，还有上一个issue的ace打头的。

**Comment by LanLan69** [comment]
discord.com

**Comment by QIN2DIM** [comment]
哦豁，这两个 sitekey 都是 discord 的吗

**Comment by QIN2DIM** [comment]
太真实，专挑我睡觉时间更新。要不是我这两天熬夜打游戏- -还真就错过了这葩怪事
