### ISSUE TITLE
[Challenge] smiling ԁog

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#87]
### Prompt[en]

Please click each image containing a smiling ԁog

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34

### Screenshot of the challenge

<img width="385" alt="截屏2022-07-15 16 48 21" src="https://user-images.githubusercontent.com/62018067/179776946-4d9b4ddc-100d-469c-90f5-d48bd899f591.png">

**Comment by QIN2DIM** [comment]
蚌珠了

**Comment by LanLan69** [comment]
笑死我了好惨

**Comment by QIN2DIM** [comment]
This is a very challenging classification problem. Why do you think it is laughing/smiling?😂

![I8thoEAGly](https://user-images.githubusercontent.com/62018067/180413696-d8d21970-4531-431a-ac0b-03033f762b95.jpg)![NtmlQ5dO9w](https://user-images.githubusercontent.com/62018067/180413782-9ee941d0-f115-465e-8878-1bfba518c307.jpg)
