### ISSUE TITLE
[Re-train] Please click on the largest animal.

### ISSUE THREAD

**Issue by deepakkumar132** [QIN2DIM/hcaptcha-challenger#881]
### Prompt[en]

Please click on the largest animal.

### request_type

image_label_binary (for ex. Please click each image containing a fox)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=discord.com

### Screenshot of the challenge

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/91746542/5bf4bef2-2e00-4255-8f74-feaff8c9dd49)

**Comment by QIN2DIM** [comment]
@deepakkumar132 

I'll provide a self-supervised use case later, so if I don't update the model in time, please use the CLIP model for the zero-shot classification task.
