### ISSUE TITLE
feat(add): Handle `airplane in the sky flying left` challenge with SK-IMAGE solution

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#9]
## Usage

You can run the demo project associated with the solution by running the following command:

```bash
# hcaptcha-challenge/src
python3 main.py demo_v3
```

## Linked pull requests

@beiyuouo https://github.com/QIN2DIM/hcaptcha-challenger/commit/30ae3915b95e65cedfd9d0d8a9896bfdd9cd114f

## Demo

![skimage-solution-2](https://user-images.githubusercontent.com/62018067/156694812-c52926e1-8d6d-4127-a241-94f5d742a694.gif)

**Comment by adv-zl** [comment]
A lot of false-positive results occurred. How is it possible to train model or expand rainbow_table?

**Comment by QIN2DIM** [comment]
@adv-zl 
The programme is designed with pass rates as an indicator, not accuracy.🛴 In terms of what you feel the programme's accuracy rate is probably at....

**Comment by QIN2DIM** [comment]
`rainbow_table` stores the MD5 value of the correct challenge image.Therefore, you need to do two things: collect enough correct use cases and convert them into MD5 strings.

**Comment by QIN2DIM** [comment]
`SK-IMAGE` is a technology for image recognition, this solution does not involve knowledge of deep learning.

Noteworthy, feature engineering can be extremely fast when set up properly, but it is a very difficult mathematical problem to improve the generalisation and accuracy of feature engineering.

**Comment by QIN2DIM** [comment]
Obviously, we will improve the solution and increase the accuracy rate in subsequent versions. 

Of course, I would love to share my thoughts on the optimisation of the solution, but there are some obstacles to this. On the one hand, the optimisation problem is too abstract, and secondly, I am concerned that I am not able to express my ideas accurately in English.

**Comment by skrrppop** [comment]
Yeah i ran 100 it times and only got it 15 trimes working

**Comment by QIN2DIM** [comment]
@skrrppop WHAT👀 I don't quite understand what you mean.Do you mean calling methods in the lab environment to test on local images, or are you using the demo to register a bunch of bot accounts?

**Comment by QIN2DIM** [comment]
> Yeah i ran 100 it times and only got it 15 times working

I'm trying to upgrade the solution, but I can't find a `sitekey` that consistently refreshes this label.

**Comment by QIN2DIM** [comment]
> `rainbow_table` stores the MD5 value of the correct challenge image.Therefore, you need to do two things: collect enough correct challenge-images and convert them into MD5 strings.

It is worth stating that the `rainbow_table` containing the MD5 of correct images is not fully manually annotated. I will undertake a large scale challenge based on existing methods and filter outputs based on the annotation results given by the model.

**Comment by skrrppop** [comment]
> > Yeah i ran 100 it times and only got it 15 times working
> 
> I'm trying to upgrade the solution, but I can't find a `sitekey` that consistently refreshes this label.

Discord ` site_key="f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34",
    site_url="https://discord.com",`
Here are only airplane in the sky flying left

**Comment by skrrppop** [comment]
> @skrrppop WHAT👀 I don't quite understand what you mean.Do you mean calling methods in the lab environment to test on local images, or are you using the demo to register a bunch of bot accounts?

I tested it with the pyhcaptcha library to solve it without need of selenium

**Comment by QIN2DIM** [comment]
This sounds really cool. Is this the library you are referring to? [PyCAPTCHA](https://pypi.org/project/PyCAPTCHA/)

**Comment by skrrppop** [comment]
I Used this Here https://github.com/h0nde/py-hcaptcha

**Comment by QIN2DIM** [comment]
> Discord ` site_key="f5561ba9-8f1e-40ca-9b5b-a0b3f719ef34", site_url="https://discord.com",` Here are only airplane in the sky flying left
 
Great help!

I'm working on a reinforcement learning pattern matching that can double the recognition accuracy.

**Comment by adv-zl** [comment]
> > Yeah i ran 100 it times and only got it 15 times working
> 
> I'm trying to upgrade the solution, but I can't find a `sitekey` that consistently refreshes this label.

Better use sitekey=4c672d35-0701-42b2-88c3-78380b0db560

**Comment by QIN2DIM** [comment]
Thank you for your work. 

Apparently there is a regular refresh of the challenge labels, `airplane in the sky flying left` only appears in some specific time period. This time period may be fixed, or it may be related to the heat of the site visit.
