### ISSUE TITLE
[Challenge] conference room

### ISSUE THREAD

**Issue by QIN2DIM** [QIN2DIM/hcaptcha-challenger#90]
### Prompt[en]

Please click each image containing a conference room

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=ace50dd0-0d68-44ff-931a-63b670c7eed7

### Screenshot of the challenge

![img_v2_15c83d78-d311-4bf6-9121-6f30785f7a8g](https://user-images.githubusercontent.com/62018067/179938605-234c7907-42c0-4868-a8e9-445db9205a0a.png)

**Comment by SpotnikSignal** [comment]
Jup got that one also :( didn't know they add these challenges so fast lol

**Comment by QIN2DIM** [comment]
who is jup😶‍🌫️

**Comment by SpotnikSignal** [comment]
> 

That means Yes or Yea haha :p
