### ISSUE TITLE
[Challenge] Please click each image containing a land animal

### ISSUE THREAD

**Issue by ndtrongvn** [QIN2DIM/hcaptcha-challenger#903]
### Prompt[en]

Please click each image containing a land animal

### request_type

image_label_binary (for ex. Please click each image containing a fox)

### Sitekey

91e4137f-95af-4bc9-97af-cdcedce21c8c

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=91e4137f-95af-4bc9-97af-cdcedce21c8c

### Screenshot of the challenge

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/37130428/6a278b6b-ba0d-48ce-b4fb-f0d92d3e4381)

**Comment by QIN2DIM** [comment]
clip
