### ISSUE TITLE
[Question] doesn't download models since I updated the pypi package.

### ISSUE THREAD

**Issue by diegoooooooooooooooo** [QIN2DIM/hcaptcha-challenger#942]
I was on an old version so I updated package pypi and am currently trying to resolve the hcaptcha, and I notice that it no longer downloads the templates to resolve these

![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/38768160/0b73138a-709d-4ce1-ba1a-dea201a977b4)

so I install hcaptcha like this at the start of the script
```python
import hcaptcha_challenger
hcaptcha_challenger.install(upgrade=True)
`

puis je procede comme cela pour tenter d'obtenir une réponse 

`
@staticmethod
async def auto_solve(question: str, tasklist: dict, job_mode: str, requester_question_example: dict) -> dict:
        log.debug("Solving captcha with AutoSolver.")
        log.debug(job_mode)
        print("question: ", question)
        print("job_mode: ", job_mode)
        answers = {}

        images = []
        for uuid, url in tasklist.items():
            images.append(await get_url(url, False))

        images_requester_question_example = []
        if requester_question_example is not None:
            for url in requester_question_example:
                images_requester_question_example.append(await get_url(url, False))

        def _auto_solve():
            try:
                #hcaptcha_challenger.install(upgrade=True)
                challenger = None

                # Sélection du classifier approprié en fonction du job_mode
                if job_mode == "image_label_binary":
                    challenger = hcaptcha_challenger.BinaryClassifier()
                elif job_mode == "image_label_area_select":
                    challenger = hcaptcha_challenger.AreaSelector()

                # Vérifiez si le challenger a été défini et exécutez-le
                if challenger:
                    if job_mode == "image_label_area_select":
                        return challenger.execute(question, images, shape_type="point")
                    else:
                        if "largest animal" in question or "the smallest animal" in question:
                            return challenger.execute(question, images, images_requester_question_example)
                        else:
                            return challenger.execute(question, images)
                else:
                    log.debug("Unsupported job mode.")
                    return None
            except Exception as e:
                log.debug(f"Error while solving captcha: {e}")
                return None

        res = await get_event_loop().run_in_executor(ThreadPoolExecutor(4), _auto_solve)
        log.debug(f"AutoSolver result: {res}")
        print(f"AutoSolver result: {res}")
        if res:
            for idx, uuid in enumerate(tasklist.keys()):
                if job_mode == "image_label_binary":
                    answers[uuid] = "true" if res[idx] else "false"
                elif job_mode == "image_label_area_select":
                    # Assurez-vous que les résultats contiennent des données valides
                    if res[idx] and len(res[idx]) > 0:
                        best = sorted(res[idx], key=lambda x: x[-1])[-1]
                        class_name, (center_x, center_y), score = best
                        answers[uuid] = [{
                            "entity_coords": [center_x, center_y],
                            "entity_name": 0,
                            "entity_type": "default"
                        }]

        log.debug(f"Answers: {answers}")
        return answers
```

I am working on the following script:
https://github.com/QIN2DIM/aio-hcaptcha

thank you in advance for your help

**Comment by diegoooooooooooooooo** [comment]
I downgraded the version to version 0.8.10.post2 and I did it like this
`
def _auto_solve():
            try:
                hcaptcha_challenger.install(upgrade=True, flush_yolo=[hcaptcha_challenger.DEFAULT_KEYPOINT_MODEL])
                challenger = None

                # Sélection du classifier approprié en fonction du job_mode
                if job_mode == "image_label_binary":
                    challenger = hcaptcha_challenger.BinaryClassifier()
                elif job_mode == "image_label_area_select":
                    challenger = hcaptcha_challenger.AreaSelector()

                # Vérifiez si le challenger a été défini et exécutez-le
                if challenger:
                    if job_mode == "image_label_area_select":
                        return challenger.execute(question, images, shape_type="point")
                    else:
                        if "largest animal" in question or "the smallest animal" in question:
                            return challenger.execute(question, images, images_requester_question_example)
                        else:
                            return challenger.execute(question, images)
                else:
                    log.debug("Unsupported job mode.")
                    return None
            except Exception as e:
                log.debug(f"Error while solving captcha: {e}")
                return None

        res = await get_event_loop().run_in_executor(ThreadPoolExecutor(4), _auto_solve)
        log.debug(f"AutoSolver result: {res}")
        print(f"AutoSolver result: {res}")
        if res:
            for idx, uuid in enumerate(tasklist.keys()):
                if job_mode == "image_label_binary":
                    answers[uuid] = "true" if res[idx] else "false"
                elif job_mode == "image_label_area_select":
                    # Assurez-vous que les résultats contiennent des données valides
                    if res[idx] and len(res[idx]) > 0:
                        best = sorted(res[idx], key=lambda x: x[-1])[-1]
                        class_name, (center_x, center_y), score = best
                        answers[uuid] = [{
                            "entity_coords": [center_x, center_y],
                            "entity_name": 0,
                            "entity_type": "default"
                        }]

        log.debug(f"Answers: {answers}")
        return answers
`
it works fine like that but I would like to upgrade to the latest version how to do it exactly

**Comment by QIN2DIM** [comment]
What do you mean by `templates`， `challegne-image-examples`?

**Comment by QIN2DIM** [comment]
[aio-hcaptcha](https://github.com/QIN2DIM/aio-hcaptcha) is just a copy of [RuslanUC/aio-hcaptcha](https://github.com/RuslanUC/aio-hcaptcha) that I used to research the [RuslanUC/aio-hcaptcha](https://github.com/RuslanUC/aio-hcaptcha) fork, this project seems to be no longer maintained and many of the design details in it no longer work.

**Comment by QIN2DIM** [comment]
So, I actually don't know what you're asking yet, I can't reproduce your question.

**Comment by QIN2DIM** [comment]
By the way, I read the example code you just provided, and I think it is not elegant enough. There are actually many bugs.



Hcaptcha modified the interface, https://hcaptcha.com/getcaptcha/{self.sitekey}

**Comment by diegoooooooooooooooo** [comment]
Voici la traduction de votre message en anglais :

Hello,

Thank you for your response. I'll try to clarify the issue I'm encountering.

When I update hcaptcha-challenger and run my program, everything seems to work correctly except for the updating and downloading of models. The models are not automatically downloaded, which leads to the failure of captcha resolution.

However, when I use version 0.8.10-post2 of hcaptcha-challenger, everything works as expected, including downloading and using the models to solve captchas.

I suspect the problem is related to this line of code: hcaptcha_challenger.install(upgrade=True, flush_yolo=[hcaptcha_challenger.DEFAULT_KEYPOINT_MODEL]). It seems that hcaptcha_challenger.DEFAULT_KEYPOINT_MODEL is no longer recognized or functions differently in the updated version.

To better illustrate the issue, here is a snippet of my code that I use for testing captcha resolution:
```python 
import asyncio
import time
from concurrent.futures import ThreadPoolExecutor
from async_hcaptcha import AioHcaptcha

async def solve_captcha_async(solver):
    start_time = time.time()  # Start the timer
    resp = None
    while resp is None:
        resp = await solver.solve(10)
    elapsed_time = time.time() - start_time  # Calculate elapsed time
    return resp, elapsed_time  # Return the response and elapsed time

def solve_captcha(solver):
    return asyncio.run(solve_captcha_async(solver))

async def main():
    solver = AioHcaptcha(
        "a5f74b19-9e45-40e0-b45d-47ff91b7a6c2",
        "https://accounts.hcaptcha.com/demo",
        {"executable_path": "chromedriver.exe"},
    )
    resp = None
    start_time = time.time()  # Start the timer

    while resp is None:
        resp = await solver.solve(10)

    end_time = time.time()  # Stop the timer
    elapsed_time = end_time - start_time  # Calculate elapsed time

    print(f"Response obtained in {elapsed_time} seconds")
    print(resp)

if __name__ == "__main__":
    asyncio.run(main())

```
Could you please help me understand why the models are not being downloaded in the latest version and how I might resolve this issue?

**Comment by QIN2DIM** [comment]
I have removed DEFAULT_KEYPOINT_MODEL from hcaptcha_challenger.__init__.py

Like I said, there are so many holes in your project... You debug first. If you are sure that the problem is coming from the hcaptcha-challenger let me look at it again, I will first make a feature to isolate the "scenario switcher"

**Comment by diegoooooooooooooooo** [comment]
ok I will debug to find out where exactly the problem comes from, thank you

**Comment by QIN2DIM** [comment]
just do this `install(upgrade=True)`

**Comment by diegoooooooooooooooo** [comment]
while doing a debug I think I found it, basically I send images in byte for a captcha like this "Please click on each image containing the smallest animal in real life" and he gives me this error
![image](https://github.com/QIN2DIM/hcaptcha-challenger/assets/38768160/d3229910-9f2b-4428-9dda-2907c45aa5f6)
which tells me that it is waiting for a path and not a byte image, it must come from images_requester_question_example if I'm not saying anything stupid.

how can I do ? Do I absolutely have to save it to send it or can I do something else here is my function

```python 
async def auto_solve(question: str, tasklist: dict, job_mode: str, requester_question_example: dict) -> dict:
        log.debug("Solving captcha with AutoSolver.")
        log.debug(job_mode)
        print("question: ", question)
        print("job_mode: ", job_mode)
        answers = {}

        images = []
        for uuid, url in tasklist.items():
            images.append(await get_url(url, False))

        images_requester_question_example = []
        if requester_question_example is not None:
            for url in requester_question_example:
                images_requester_question_example.append(await get_url(url, False))

        def _auto_solve():
            try:
                hcaptcha_challenger.install(upgrade=True)
                challenger = None

                # Sélection du classifier approprié en fonction du job_mode
                if job_mode == "image_label_binary":
                    challenger = hcaptcha_challenger.BinaryClassifier()
                elif job_mode == "image_label_area_select":
                    challenger = hcaptcha_challenger.AreaSelector()

                # Vérifiez si le challenger a été défini et exécutez-le
                if challenger:
                    if job_mode == "image_label_area_select":
                        return challenger.execute(question, images, shape_type="point")
                    else:
                        if "largest animal" in question or "the smallest animal" in question:
                            return challenger.execute(question, images, images_requester_question_example)
                        else:
                            return challenger.execute(question, images)
                else:
                    print("Unsupported job mode.")
                    return None
            except Exception as e:
                print(f"Error while solving captcha: {e}")
                traceback.print_exc()
                return None

        res = await get_event_loop().run_in_executor(ThreadPoolExecutor(4), _auto_solve)
        log.debug(f"AutoSolver result: {res}")
        print(f"AutoSolver result: {res}")
        if res:
            for idx, uuid in enumerate(tasklist.keys()):
                if job_mode == "image_label_binary":
                    answers[uuid] = "true" if res[idx] else "false"
                elif job_mode == "image_label_area_select":
                    # Assurez-vous que les résultats contiennent des données valides
                    if res[idx] and len(res[idx]) > 0:
                        best = sorted(res[idx], key=lambda x: x[-1])[-1]
                        class_name, (center_x, center_y), score = best
                        answers[uuid] = [{
                            "entity_coords": [center_x, center_y],
                            "entity_name": 0,
                            "entity_type": "default"
                        }]

        log.debug(f"Answers: {answers}")
        return answers
```
the problem comes from this line
return challenger.execute(question, images, images_requester_question_example)

**Comment by QIN2DIM** [comment]
https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/examples/demo_classifier_common.py

I updated the function signature a long time ago that you should pass in the path of the saved image, not the bytes of the image

**Comment by QIN2DIM** [comment]
example_path.read_bytes() 

Obviously, this example_path is a pathlib.Path object

**Comment by QIN2DIM** [comment]
I will update some incompatible features in the next release, and then fix an asynchronous deadlock issue.

**Comment by diegoooooooooooooooo** [comment]
Ok great, thanks in advance
