### ISSUE TITLE
[Challenge] horse made of clouds

### ISSUE THREAD

**Issue by vgabs** [QIN2DIM/hcaptcha-challenger#96]
### Prompt[en]

Please click each image containing a horse made of clouds

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

edc4ce89-8903-4906-80b1-7440ad9a69c8

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=edc4ce89-8903-4906-80b1-7440ad9a69c8

### Screenshot of the challenge

![image](https://user-images.githubusercontent.com/34200697/180748767-c004ec84-e83a-4cd9-a43c-8134b2904c0c.png)

**Comment by QIN2DIM** [comment]
ପ( ˘ᵕ˘ ) ੭ ☆

**Comment by potentful** [comment]
these captcha's getting outlandishly ridiculous haha

**Comment by QIN2DIM** [comment]
@potentful https://github.com/QIN2DIM/hcaptcha-challenger/issues/36

**Comment by potentful** [comment]
> @potentful #36

LOL

**Comment by QIN2DIM** [comment]
The GAN model seems to be working pretty well this time, and I expect new challenges to come in the near future ~ `elephant made of clouds`
