### ISSUE TITLE
[Challenge] dog with closed eyes

### ISSUE THREAD

**Issue by huozhenlin** [QIN2DIM/hcaptcha-challenger#98]
### Prompt[en]

Please click each image containing a dog with closed eyes

### New types of challenge

New prompt (for ex. Please select all the 45th President of the US)

### Sitekey

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Sitelink

https://accounts.hcaptcha.com/demo?sitekey=8adc2f3e-e343-4ef9-bf6c-275a8a2818ab

### Screenshot of the challenge

<img width="55%" src="https://user-images.githubusercontent.com/19356940/181439862-bd2fac88-3cfa-49c5-88a4-13454c752779.png"> <img width="45%" src="https://user-images.githubusercontent.com/62018067/181485242-2d131cce-8502-4951-87bb-35339bb9fd02.png">

**Comment by QIN2DIM** [comment]
无法复现

**Comment by adv-zl** [comment]
[https://accounts.hcaptcha.com/demo?sitekey=a9b5fb07-92ff-493f-86fe-352a2803b3df](https://accounts.hcaptcha.com/demo?sitekey=a9b5fb07-92ff-493f-86fe-352a2803b3df)

**Comment by liuming9157** [comment]
【一只闭着眼睛的狗】最近出现频率很高

**Comment by QIN2DIM** [comment]
最近在准备面经和算法题打算搬砖去了- -没太多时间泡 GitHub，我前段时间写了一套自动化的框架可以预警+自动训练单目标模型，但是模型校验以及更新 GitHub 这边的数据总是会慢半拍。
