### ISSUE TITLE
[Question] Tactical retreat

### ISSUE THREAD

**Issue by MRakox** [QIN2DIM/hcaptcha-challenger#99]
## Brief description

Hello !
I'm getting errors on challenges that should work (for example `conference room`, see below for full warning message).
I tried to figure out what the problem could be and obviously the function that wouldn't work would be `tactical_retreat`. In some cases, the value of `self.label_alias.get(self.label)` is `None` so the challenge is ignored.

## Some examples

```markdown
WARNING - >> ALERT [ArmorCaptcha] Types of challenges not yet scheduled - label=「conference room」 prompt=「Please click each image containing a conference room」 screenshot=/hcaptcha_challenger/src/database/temp_cache/captcha_screenshot/1658996689.conference room.png site_link=[redacted] issues=https://github.com/QIN2DIM/hcaptcha-challenger/issues?q=conference+room

WARNING - >> ALERT [ArmorCaptcha] Types of challenges not yet scheduled - label=「lion」 prompt=「Please click each image containing a lion」 screenshot=/hcaptcha_challenger/src/database/temp_cache/captcha_screenshot/1658996698.lion.png site_link=[redacted] issues=https://github.com/QIN2DIM/hcaptcha-challenger/issues?q=lion

WARNING - >> ALERT [ArmorCaptcha] Types of challenges not yet scheduled - label=「smiling dog」 prompt=「Please click each image containing a smiling dog」 screenshot=/hcaptcha_challenger/src/database/temp_cache/captcha_screenshot/1658996701.smiling dog.png site_link=[redacted] issues=https://github.com/QIN2DIM/hcaptcha-challenger/issues?q=smiling+dog
```

And every time this issue occured, the value of  `self.label_alias.get(self.label)` is `None`.

> I think it would be enough to update the `label_alias` dictionary (https://github.com/QIN2DIM/hcaptcha-challenger/blob/main/src/services/hcaptcha_challenger/core.py#L38) to integrate the new challenges and solve the problem.

Sincerely,

**Comment by QIN2DIM** [comment]
Are you using the most recent version of the code

**Comment by MRakox** [comment]
yes of course, I'm on `5fa30fc4877fb2c76b5e4dae34875371fd5176a1`.

**Comment by QIN2DIM** [comment]
I wrote all these pluggable models in the file objects.yaml. You can try to insert the code `print(self.label_alias)` to `ArmorCaptcha().init()` and run the program.

**Comment by QIN2DIM** [comment]
After the following code

https://github.com/QIN2DIM/hcaptcha-challenger/blob/5fa30fc4877fb2c76b5e4dae34875371fd5176a1/src/services/hcaptcha_challenger/core.py#L149-L156

**Comment by MRakox** [comment]
Thank you !
I'll try in a few minutes...

**Comment by MRakox** [comment]
Here is the output :
```
{
   "airplane":"airplane",
   "motorbus":"bus",
   "bus":"bus",
   "truck":"truck",
   "motorcycle":"motorcycle",
   "boat":"boat",
   "bicycle":"bicycle",
   "train":"train",
   "vertical river":"vertical river",
   "airplane in the sky flying left":"airplane in the sky flying left",
   "Please select all airplanes in the sky that are flying to the right":"airplanes in the sky that are flying to the right",
   "car":"car",
   "elephant":"elephant"
}
```

**Comment by QIN2DIM** [comment]
If you make any changes to the source code, you'll need to do it yourself.

**Comment by QIN2DIM** [comment]
Maybe you need to re-clone a project file to do the same test.
